#+title: Números reais
#+author: Max Jauregui
#+language: pt_BR
#+LATEX_CLASS_OPTIONS: [12pt,a4paper]
#+latex_header: \setlength{\parindent}{0em}
#+latex_header: \setlength{\parskip}{1ex}
#+latex_header: \usepackage[portuguese]{babel}
#+latex_header: \usepackage[stable]{footmisc}
#+latex_header: \usepackage{mathabx}

# This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.

* Linguagem de conjuntos

Um *conjunto* $A$ é uma coleção de objetos quaisquer, chamados de *elementos* de $A$.
Se $x$ é um elemento de $A$, diz-se que $x$ *pertence* a $A$ e escreve-se $x\in A$; caso contrário, escreve-se $x\not\in A$.

*Exemplo.* Se $A=\{1,2,3\}$, temos que $1\in A$ e $4\not\in A$.

O *conjunto vazio*, denotado por $\emptyset$, é o conjunto que não tem elementos.

Sejam $A$ e $B$ conjuntos. Diz-se que $A$ está *contido* em $B$ ou que $A$ é um *subconjunto* de $B$ se $x\in A$ implica que $x\in B$.

*Exemplo.* Sejam $A=\{1,2,3\}$, $B=\{1,2,3,4\}$ e $C=\{2,3,4,5\}$. Temos que $A\subset B$; porém, $A\not\subset C$.

Sejam $A$ e $B$ conjuntos.

1. Define-se a *união* de $A$ e $B$, denotada por $A\cup B$, como o conjunto formado por todos os elementos de $A$ e $B$, ou seja,
 $$A\cup B=\{x:x\in A\text{ ou }x\in B\}\,.$$
2. Define-se a *interseção* de $A$ e $B$, denotada por $A\cap B$, como o conjunto formado por todos os elementos que $A$ e $B$ têm em comum, ou seja,
 $$A\cap B=\{x:x\in A\text{ e }x\in B\}\,.$$
3. Define-se a *diferença* $A-B$ como o conjunto formado por todos os elementos de $A$ que não pertencem a $B$, ou seja,
 $$A-B=\{x\in A:x\not\in B\}\,.$$
4. Define-se o *produto cartesiano* $A\times B$ como o conjunto de todos os pares ordenados $(x,y)$, com $x\in A$ e $y\in B$, ou seja,
 $$A\times B=\{(x,y):x\in A\text{ e }y\in B\}\,.$$
 Dois pares ordenados $(x_1,y_1)$ e $(x_2,y_2)$ são iguais se e somente se $x_1=x_1$ e $y_1=y_2$.

*Exemplo.* Sejam $A=\{1,2,3,4\}$ e $B=\{1,3,5\}$. Temos que $A\cup B=\{1,2,3,4,5\}$, $A\cap B=\{1,3\}$, $A-B=\{2,4\}$, $B-A=\{5\}$ e
$$A\times B=\{(1,1),(1,3),(1,5),(2,1),(2,3),(2,5),(3,1),(3,3),(3,5),(4,1),(4,3),(4,5)\}\,.$$

* Funções

Sejam $A$ e $B$ conjuntos. Uma *função* $f$ de $A$ em $B$ pode ser definida como um subconjunto de $A\times B$ tal que para cada $x\in A$ existe um único par ordenado $(x,y)\in f$.

*Exemplo.* Se $A=\{1,2,3\}$ e $B=\{10,20\}$, o conjunto
$$f=\{(1,10),(2,10),(3,20)\}$$
é uma função de $A$ em $B$. No entanto, os conjuntos
$$g=\{(1,10),(1,20),(2,20),(3,20)\}\quad\text{e}\quad h=\{(1,20),(3,20)\}$$
não são funções de $A$ em $B$.

Seja $f$ uma função de $A$ em $B$. Se $(x,y)\in f$, diz-se que $y$ é o *valor* da função $f$ no ponto $x$ e escreve-se $y=f(x)$.

*Exemplo.* Para a função $f$ do exemplo anterior temos que $f(1)=10$, $f(2)=10$ e $f(3)=20$.

Uma função $f$ de $A$ em $B$ é denotada simbolicamente por $f:A\to B$.
O conjunto $A$ é chamado de *domínio* de $f$ e o conjunto $B$ de *contradomínio* de $f$.
Pode-se definir uma função $f:A\to B$ fornecendo uma regra que permita encontrar o valor $f(x)\in B$ para cada $x\in A$.

*Exemplo.* Se $A=\{1,2,3,4,5\}$ e $B=\{1,3,5\}$, podemos definir uma função $f:A\to B$ pondo, por exemplo,
$$f(x)=\begin{cases}
1&\text{se }x\text{ é ímpar}\\
3&\text{se }x\text{ é par.}\\
\end{cases}$$

Dada uma função $f:A\to B$, define-se a *imagem de um conjunto* $E\subset A$ por $f$ como o conjunto
$$f(E)=\{f(x):x\in A\}\,.$$
O conjunto $f(A)$ é chamado de *imagem da função* $f$.

*Exemplo.* A imagem da função $f$ do exemplo anterior é o conjunto $f(A)=\{1,3\}$.

Diz-se que uma função $f:A\to B$ é *injetiva* se para quaisquer $x_1,x_2\in A$ com $x_1\ne x_2$ tem-se que $f(x_1)\ne f(x_2)$.

*Exemplo.* Sejam $A=\{1,2,3\}$ e $B=\{4,5,6,7\}$. A função $f:A\to B$ definida por $f(x)=x+3$ é injetiva.
No entanto, a função $g:A\to B$ definida por $g(x)=6$ não é injetiva.

Uma função $f:A\to B$ é dita *sobrejetiva* se $f(A)=B$.

*Exemplo.* Sejam $A=\{1,2,3,4\}$ e $B=\{4,5,6\}$. A função $f:A\to B$ definida por
 $$f(x)=\begin{cases}
x+3&\text{se }x\ne 4\\
4&\text{se }x=4
\end{cases}$$
é sobrejetiva. No entanto, a função $g:A\to B$, definida por
$$g(x)=\begin{cases}
5&\text{se }x\text{ é ímpar}\\
6&\text{se }x\text{ é par}\\
\end{cases}$$
não é sobrejetiva.

Diz-se que uma função $f:A\to B$ é *bijetiva* ou que é uma *bijeção* se ela é injetiva e sobrejetiva.

*Exemplo.* Sejam $A=\{1,2,3\}$ e $B=\{4,5,6\}$. A função $f:A\to B$ definida por $f(x)=x+3$ é uma bijeção.

Sejam $f:A\to B$ e $g:C\to D$ duas funções. Se $f(A)\subset C$, define-se a *função composta* $g\circ f:A\to D$ por $(g\circ f)(x)=g(f(x))$.

*Exemplo.* Dados os conjuntos $A=\{1,2,3\}$, $B=\{4,5,6\}$ e $C=\{2,3,4\}$, consideremos as funções $f:A\to B$ e $g:B\to D$ definidas respectivamente por $f(x)=x+3$ e $g(x)=x-2$.
Notamos que $f(A)=B$ e, por conseguinte, podemos definir a função composta $g\circ f:A\to C$. De fato, vamos ter que
$$(g\circ f)(x)=g(x+3)=(x+3)-2=x+1$$
para todo $x\in A$. Por outro lado, como $g(B)=C\not\subset A$, a função composta $f\circ g:B\to A$ não pode ser definida.

*Teorema.* Sejam $f:A\to B$ e $g:B\to C$ funções. Tem-se o seguinte:

1. Se $f$ e $g$ são injetivas, então $g\circ f$ também é injetiva.
2. Se $f$ e $g$ são sobrejetivas, então $g\circ f$ também é sobrejetiva.
3. Se $f$ e $g$ são bijeções, então $g\circ f$ também é uma bijeção.

Seja $f:A\to B$ uma função. Diz-se que uma função $g:B\to A$ é uma *inversa à esquerda* de $f$ se $g(f(x))=x$ para todo $x\in A$.
Por outro lado, diz-se que uma função $h:B\to A$ é uma *inversa à direita* de $f$ se $f(h(x))=x$ para todo $x\in B$.

*Teorema.* Seja $f:A\to B$ uma função. Se $g:B\to A$ é uma inversa à esquerda de $f$ e $h:B\to A$ é uma inversa à direita de $f$, então $g=h=f^{-1}$.
Nesse caso, a função $f^{-1}:B\to A$ é chamada de *inversa* de $f$.

*Demonstração.* Temos que $g(f(x))=x$ para todo $x\in A$ e $f(h(y))=y$ para todo $y\in B$. Como $h(y)\in A$ para todo $y\in B$, então
$$g(y)=g(f(h(y)))=h(y)$$
para todo $y\in B$. $\blacksquare$

*Teorema.* Uma função $f:A\to B$ tem uma inversa à esquerda se, e somente se, é injetiva.

*Demonstração.* ($\Rightarrow$) Seja $g:B\to A$ uma inversa à esquerda de $f$. Se $x_1,x_2\in A$ são tais que $f(x_1)=f(x_2)$, então $x_1=g(f(x_1))=g(f(x_2))=x_2$. Logo, $f$ é injetiva.
($\Leftarrow$) Se $f$ é injetiva, para cada $y\in f(A)$ existe um único $x_y\in A$ tal que $y=f(x_y)$. Definimos então uma função $g:B\to A$ pondo
$$g(y)=\begin{cases}
x_y&\text{se }y\in f(A)\\
a&\text{se }y\not\in f(A),
\end{cases}$$
em que $a\in A$ é um elemento arbitrário. Como $g(f(x))=x$ para todo $x\in A$, temos que $g$ é uma inversa à esquerda de $f$. $\blacksquare$

*Exemplo.* Sejam $A=\{1,2,3\}$ e $B=\{4,5,6,7\}$. A função $f:A\to B$ definida por $f(x)=x+3$ é injetiva e, por conseguinte, tem uma inversa à esquerda.
Por exemplo, a função $g:B\to A$ definida por[fn:1]
$$g(x)=\begin{cases}
x-3&\text{se }x\ne 7\\
1&\text{se }x=7
\end{cases}$$
é uma inversa à esquerda de $f$.

*Teorema.* Uma função $f:A\to B$ tem uma inversa à direita se, e somente se, ela é sobrejetiva.

*Demonstração.* ($\Rightarrow$) Seja $g:B\to A$ uma inversa à direita de $f$.
Logo, para cada $y\in B$, temos que $f(g(y))=y$. Como $g(y)\in A$, segue que $f(A)=B$.
($\Leftarrow$) Se $f(A)=B$, então para cada $y\in B$ existe pelo menos um $x\in A$ tal que $f(x)=y$.
Logo, a função $g:B\to A$ definida por $g(y)=x_y$, em que $x_y\in A$ é tal que $f(x_y)=y$, é uma inversa à direita de $f$. $\blacksquare$

*Exemplo.* Sejam $A=\{1,2,3,4\}$ e $B=\{4,5,6\}$. A função $f:A\to B$ definida por
$$f(x)=\begin{cases}
x+2&\text{se }x\ne 1\\
5&\text{se }x=1
\end{cases}$$
é sobrejetiva e, por conseguinte, tem uma inversa à direita. Por exemplo, a função $g:B\to A$ definida por $g(x)=x-2$ é uma inversa à direita de $f$.

*Corolário.* Uma função $f:A\to B$ tem inversa se, e somente se, é uma bijeção.

* O corpo dos números reais[fn:2]

Um conjunto $F$ é chamado de um *corpo* se nele estão definidas duas operações, chamadas de *adição* ($+$) e *multiplicação* ($\cdot$), que têm as seguintes propriedades:

1. $x+y\in F$ para quaisquer $x,y\in F$;
2. $x+(y+z)=(x+y)+z$ para quaisquer $x,y,z\in F$;
3. $x+y=y+x$ para quaisquer $x,y\in F$;
4. existe $0\in F$ tal que $x+0=x$ para todo $x\in F$;
5. para cada $x\in F$ existe $-x\in F$ tal que $x+(-x)=0$;
6. $xy\in F$ para quaisquer $x,y\in F$;
7. $x(yz)=(xy)z$ para quaisquer $x,y,z\in F$;
8. $xy=yx$ para quaisquer $x,y\in F$;
9. existe $1\in F$, $1\ne 0$, tal que $x\cdot 1=x$ para todo $x\in F$;
10. para cada $x\in F$, $x\ne 0$, existe $x^{-1}\in F$ tal que $xx^{-1}=1$;
11. $x(y+z)=xy+xz$ para quaisquer $x,y,z\in F$.

*Exemplo.* O conjunto dos números inteiros será denotado por $\mathbb{Z}$, ou seja,
$$\mathbb{Z}=\{\ldots,-3,-2,-1,0,1,2,3,\ldots\}\,.$$
$\mathbb{Z}$ não é um corpo, pois, por exemplo, $2\in\mathbb{Z}$ mas não existe $m\in\mathbb{Z}$ tal que $2m=1$.

*Exemplo.* O conjunto dos números racionais será denotado por $\mathbb{Q}$, ou seja,
$$\mathbb{Q}=\left\{\frac{m}{n}:m,n\in\mathbb{Z},n\ne 0\right\}\,.$$
$\mathbb{Q}$ é um corpo.

Um corpo $F$ é chamado de um *corpo ordenado* se existe uma *ordem* $<$ que tem as seguintes propriedades:

1. dados $x,y\in F$ quaisquer, só uma das seguintes afirmações é verdadeira: $x< y$, $x=y$ ou $y< x$;
2. se $x,y,z\in F$, $x< y$ e $y< z$, então $x< z$;
3. se $x,y\in F$ e $x< y$, então $x+z< y+z$ para todo $z\in F$;
4. se $x,y,z\in F$, $x< y$ e $0< z$, então $xz< yz$.

*Exemplo.* $\mathbb{Q}$ é um corpo ordenado.

Seja $F$ um corpo ordenado. Diz-se que um conjunto $A\subset F$ é *limitado superiormente* se existe $b\in F$ tal que $x< b$ para todo $x\in A$.
Nesse caso, diz-se também que $b$ é uma *cota superior* de $A$. Seja $A\subset F$ um conjunto limitado superiormente. Se existe $\beta\in F$ tal que

1. $\beta$ é uma cota superior de $A$;
2. se $b$ é uma cota superior de $A$, então $\beta\le b$;

então diz-se que $\beta$ é o *supremo* de $A$ e escreve-se $\beta=\sup A$.

Diz-se que um conjunto $A\subset F$ é *limitado inferiormente* se existe $a\in F$ tal que $x> a$ para todo $x\in A$.
Nesse caso, diz-se também que $a$ é uma *cota inferior* de $A$. Seja $A\subset F$ um conjunto limitado inferiormente. Se existe $\alpha\in F$ tal que

1. $\alpha$ é uma cota inferior de $A$;
2. se $\alpha$ é uma cota inferior de $A$, então $\alpha\ge a$;

então diz-se que $\alpha$ é o *ínfimo* de $A$ e escreve-se $\alpha=\inf A$.

Diz-se que um corpo ordenado $F$ é *completo* se todo subconjunto de $F$ não-vazio e limitado superiormente tem um supremo.

*Exemplo.* Vamos mostrar que $\mathbb{Q}$ não é um corpo ordenado completo. Para isso primeiramente vamos mostrar que não existe $r\in\mathbb{Q}$ tal que $r^2=2$.
Se isso fosse verdade existiriam inteiros positivos $m$ e $n$ primos relativos tais que $r=m/n$ e $r^2=2$. Logo, teríamos que $m^2=2n^2$ e, por conseguinte, $m=2k$ para algum inteiro positivo $k$.
No entanto, isso implicaria que $2k^2=n^2$ e, por conseguinte, $n$ e $m$ seriam ambos pares, contradizendo a hipótese inicial de que $m$ e $n$ eram primos relativos. Portanto, se $r^2=2$, $r$ não pode ser racional.
Agora consideremos o conjunto
$$A=\{x\in\mathbb{Q}:x^2< 2\}\,.$$
Notamos que $A$ é não-vazio e que $2$ é uma cota superior de $A$, pois $x\ge 2$ implica que $x\not\in A$.
No entanto, vamos mostrar que $A$ não tem supremo em $\mathbb{Q}$.
Se $\beta\in\mathbb{Q}$ fosse o supremo de $A$, em virtude do que mostramos no início do exemplo, só teríamos duas possibilidades: $\beta^2< 2$ ou $\beta^2>2$.
Se $\beta^2< 2$, podemos encontrar um $h\in\mathbb{Q}$ tal que $0< h <1$ e $\displaystyle h< \frac{2-\beta^2}{2\beta+1}$. Logo,
$$(\beta+h)^2=\beta^2+2\beta h+h^2< \beta^2+(2\beta+1)h< 2$$
e, por conseguinte, $\beta+h\in A$, contradizendo a hipótese de que $\beta=\sup A$. Por outro lado, se $\beta^2>2$, podemos encontrar $h\in\mathbb{Q}$ tal que $\displaystyle 0< h< \frac{\beta^2-2}{2\beta}$. Logo, se $x\ge \beta-h$, então
$$x^2\ge (\beta-h)^2=\beta^2-2\beta h+h^2\ge \beta^2-2\beta h>2$$
e, por conseguinte, $\beta-h$ é uma cota superior de $A$, contradizendo a hipótese de que $\beta=\sup A$. Portanto, como não podemos ter $\beta^2< 2$ ou $\beta^2>2$, o conjunto $A$ não tem supremo em $\mathbb{Q}$.

Define-se o corpo dos *números reais*, denotado por $\mathbb{R}$, como um corpo ordenado completo que contém o corpo dos números racionais. O conjunto $\mathbb{R}-\mathbb{Q}$ é chamado de conjunto dos *números irracionais*.

*Teorema ($\mathbb{R}$ é arquimediano).* Se $x,y\in\mathbb{R}$ e $x>0$, existe um inteiro $n>0$ tal que $nx>y$.

*Demonstração.* Se $x>y$, o teorema é trivial. Se $x< y$, consideremos o conjunto $A=\{nx\in\mathbb{R}:n\in\mathbb{Z},n>0\}$.
Temos que $A$ é não-vazio. Se $A$ fosse limitado superiormente, existiria $\beta=\sup A$.
Logo, como $\beta-x$ não seria uma cota superior de $A$, existiria um inteiro $n>0$ tal que $\beta-x\le nx$.
Porém, isso implicaria que $\beta\le (n+1)x$, contradizendo a hipótese de que $\beta=\sup A$.
Logo, $A$ não pode ser limitado superiormente e, por conseguinte, $y$ não pode ser uma cota superior de $A$, ou seja, existe um inteiro $n>0$ tal que $nx>y$. $\blacksquare$

*Corolário.* $\displaystyle\inf\left\{\frac{1}{n}:n\in\mathbb{Z},n>0\right\}=0$.

*Teorema ($\mathbb{Q}$ é denso em $\mathbb{R}$).* Dados $x,y\in\mathbb{R}$ quaisquer tais que $x< y$, existe $r\in\mathbb{Q}$ tal que $x< r< y$.

*Demonstração.* Consideremos inicialmente que $0\le x< y$. Pelo corolário anterior existe um inteiro $n>0$ tal que $1/n< y-x$.
Consideremos agora o conjunto
$$A=\left\{m\in\mathbb{Z}:m>0,\frac{m}{n}\ge y\right\}\,.$$
Como $\mathbb{R}$ é arquimediano, temos que $A$ é não-vazio. Seja $m_0$ o menor elemento de $A$. Logo, temos que $\frac{m_0-1}{n}< y$.
Se tivéssemos $\frac{m_0-1}{n}\le x$, teríamos que
$$\frac{m_0}{n}=\frac{m_0-1}{n}+\frac{1}{n}\le x+\frac{1}{n}< y\,,$$
o que implicaria que $m_0\not\in A$. Assim, devemos ter $x< \frac{m_0-1}{n}< y$.
Se $x< y\le 0$, então $0\le -y< -x$ e, pelo que acabamos de provar, existe $r\in\mathbb{Q}$ tal que $-y< r< -x$. Portanto, $x< -r< y$.
Finalmente, o teorema é trivial no caso $x< 0< y$, pois $0\in\mathbb{Q}$. $\blacksquare$

Sejam $a,b\in\mathbb{R}$ com $a\le b$. Definem-se os seguintes *intervalos finitos*:

1. *Intervalo aberto*: $(a,b)=\{x\in\mathbb{R}:a< x< b\}$
2. *Intervalo fechado*: $[a,b]=\{x\in\mathbb{R}:a\le x\le b\}$
3. *Intervalos semiabertos*: $(a,b]=\{x\in\mathbb{R}:a< x\le b\}$ e $[a,b)=\{x\in\mathbb{R}:a\le x< b\}$

O intervalo fechado $[a,a]=\{a\}$ é chamado de *intervalo degenerado*. Definem-se também os seguintes *intervalos infinitos*:

1. $(a,\infty)=\{x\in\mathbb{R}:x>a\}$
2. $[a,\infty)=\{x\in\mathbb{R}:x\ge a\}$
3. $(-\infty,a)=\{x\in\mathbb{R}:x< a\}$
4. $(-\infty,a]=\{x\in\mathbb{R}:x\le a\}$
5. $(-\infty,\infty)=\mathbb{R}$

*Teorema dos intervalos encaixados.* Para cada inteiro $n>0$ seja $I_n$ um intervalo fechado.
Se $I_{n+1}\subset I_n$ para todo $n$, então existe $c\in\mathbb{R}$ tal que $c\in I_n$ para todo $n$.

*Demonstração.* Para cada inteiro $n>0$, seja $I_n=[a_n,b_n]$. Temos que
$$a_1\le a_2\le \ldots\le a_n\le\ldots\le b_n\le \ldots\le b_2\le b_1\,.$$
O conjunto $A=\{a_1,a_2,\ldots\}$ é um conjunto não-vazio tal que qualquer $b_n$, com $n>0$ inteiro, é uma cota superior de $A$.
Logo, existe $c=\sup A$, o qual satisfaz a desigualdade $a_n\le c\le b_n$ para todo inteiro $n>0$. $\blacksquare$

* Conjuntos enumeráveis e não-enumeráveis[fn:3]

Seja $\mathbb{Z}^+$ o conjunto dos inteiros positivos. Diz-se que um conjunto $A$ é *enumerável* se existe uma função injetiva $f:A\to \mathbb{Z}^+$.

*Exemplo.* O conjunto $A=\{a,b,c\}$ é enumerável, pois a função $f:A\to\mathbb{Z}^+$ definida por $f(a)=1$, $f(b)=2$ e $f(c)=3$ é injetiva. De fato, qualquer conjunto que tem um número finito de elementos é enumerável.

*Exemplo.* O conjunto $\mathbb{Z}$ dos números inteiros é um conjunto enumerável, pois a função $f:\mathbb{Z}\to\mathbb{Z}^+$ definida por 
$$f(n)=\begin{cases}
2n+1&\text{se }n\ge 0\\
-2n&\text{se }n<0\\
\end{cases}$$
é injetiva (de fato é uma bijeção).

*Exemplo.* O conjunto $\mathbb{Z^+}\times\mathbb{Z}^+$ é enumerável, pois a função
$f:\mathbb{Z}^+\times\mathbb{Z}^+\to\mathbb{Z}^+$ definida por
$$f(m,n)=2^m3^n$$
é injetiva em virtude da unicidade da decomposição de inteiros positivos em fatores primos.

*Teorema.* Um conjunto $A$ é enumerável se, e somente se, existe uma função sobrejetiva $f:\mathbb{Z}^+\to A$.

*Demonstração.* Suponhamos que $g:A\to\mathbb{Z}^+$ seja uma função injetiva.
Essa afirmação é equivalente a dizer que $g$ tem uma inversa à esquerda $f:\mathbb{Z}^+\to A$. A função $f$ é sobrejetiva, pois $g$ é uma inversa à direita dela. $\blacksquare$

*Teorema.* Se $A$ e $B$ são conjuntos enumeráveis, então $A\times B$ também é um conjunto enumerável.

*Demonstração.* Existem funções injetivas $f:A\to\mathbb{Z}^+$ e $g:B\to\mathbb{Z}^+$.
Podemos verificar imediatamente que a função $\phi:A\times B\to\mathbb{Z}^+\times\mathbb{Z}^+$ definida por $\phi(x,y)=(f(x),g(y))$ é injetiva.
Como $\mathbb{Z}^+\times\mathbb{Z}^+$ é enumerável, existe uma função injetiva $h:\mathbb{Z}^+\times\mathbb{Z}^+\to\mathbb{Z}$.
Logo, a função composta $h\circ \phi:A\times B\to\mathbb{Z}^+$ é injetiva e, por conseguinte, $A\times B$ é enumerável. $\blacksquare$


*Exemplo ($\mathbb{Q}$ é enumerável).* O conjunto $\mathbb{Q}$ dos números racionais é enumerável, pois a função $f:\mathbb{Z}\times\mathbb{Z}^+\to\mathbb{Q}$ definida por $f(m,n)=m/n$ é sobrejetiva e o conjunto $\mathbb{Z}\times\mathbb{Z}^+$ é enumerável.

Seja $L$ um conjunto tal que, para cada $\alpha\in L$, $A_\alpha$ seja um conjunto. Isso define uma *família de conjuntos* $(A_\alpha)_{\alpha\in L}$.
Define-se a união dessa família por
$$\bigcup_{\alpha\in L}A_\alpha=\{x:x\in A_{\alpha}\text{ para algum }\alpha\in L\}\,.$$
Define-se a interseção da família por
$$\bigcap_{\alpha\in L}A_\alpha=\{x:x\in A_{\alpha}\text{ para todo }\alpha\in L\}\,.$$

*Teorema.* Seja $(A_\alpha)_{\alpha\in L}$ uma família de conjuntos. Se $L$ é enumerável e, para cada $\alpha\in L$, $A_\alpha$ é enumerável, então a união $\bigcup_{\alpha\in L}A_\alpha$ é um conjunto enumerável.

*Demonstração.* Para cada $\alpha\in L$ existe uma função sobrejetiva $f_\alpha:\mathbb{Z}^+\to A_\alpha$.
Podemos verificar facilmente que a função $\phi:L\times L\to \bigcup_{\alpha\in L}A_\alpha$ definida por
$$\phi(\alpha,x)=f_\alpha(x)$$
é sobrejetiva. Como $L\times L$ é enumerável, segue que $\bigcup_{\alpha\in L}A_\alpha$ também é enumerável.

*Teorema ($\mathbb{R}$ é não-enumerável).* O conjunto $\mathbb{R}$ dos números reais é não-enumerável. 

*Demonstração.* Seja $E=\{x_1,x_2,\ldots\}\subset\mathbb{R}$ um conjunto enumerável arbitrário. Vamos mostrar que $\mathbb{R}\ne E$.
Para isso consideremos inicialmente um intervalo fechado não-dgenerado $I_1$ tal que $x_1\not\in I_1$.
Supondo definido o intervalo fechado não-degenerado $I_n\subset I_1$ tal que $x_n\not\in I_n$, temos as seguintes opções

1. $x_{n+1}\not\in I_n$
2. $x_{n+1}\in I_n$

No primeiro caso, definimos $I_{n+1}=I_n$ e assim $I_{n+1}\subset I_n$.
No segundo caso, $x_{n+1}$ deve ser diferente de pelo menos um dos extremos do intervalo $I_n=[a_n,b_n]$.
Logo, se, por exemplo, $x_{n+1}\ne a_n$, definimos $I_{n+1}=[a_n,(a_n+x_n)/2]$ e assim $I_{n+1}\subset I_n$.
Esse procedimento nos permite definir, para cada $n\in\mathbb{Z}^+$, um intervalo fechado não-degenerado $I_n$ tal que $x_n\not\in I_n$ e $I_{n+1}\subset I_n$ para todo $n\in\mathbb{Z}^+$.
Pelo teorema dos intervalos encaixados, existe $c\in\mathbb{R}$ tal que $c\in I_n$ para todo $n\in\mathbb{Z}^+$. Logo, $c\ne x_n$ para todo $n\in\mathbb{Z}^+$ e, por conseguinte, $c\not\in E$. $\blacksquare$

*Corolário.* O conjunto $\mathbb{R}-\mathbb{Q}$ dos números irracionais é não-enumerável.

* Footnotes

[fn:3] Esta seção pode ser omitida em uma primeira leitura. 

[fn:2] Em uma primeira leitura podem ser omitidas as demonstrações dos teoremas desta seção.

[fn:1] A expressão de $g(x)$ pode ser obtida resolvendo a equação $y=x+3$ para $x$ e depois permutando as variáveis $x$ e $y$.
