#+title: Funções reais de uma variável real
#+author: Max Jauregui
#+language: pt_BR
#+LATEX_CLASS_OPTIONS: [12pt,a4paper]
#+latex_header: \usepackage[portuguese]{babel}
#+latex_header: \usepackage[stable]{footmisc}
#+latex_header: \usepackage{mathabx}
#+latex_header: \usepackage{amsthm}
#+latex_header: \newcommand{\R}{\mathbb{R}}
#+latex_header: \newcommand{\Z}{\mathbb{Z}}
#+latex_header: \newcommand{\Q}{\mathbb{Q}}
#+latex_header: \newtheorem{thm}{Teorema}
#+latex_header: \newtheorem{cor}[thm]{Corolário}
#+latex_header: \theoremstyle{definition}
#+latex_header: \newtheorem{ex}[thm]{Exemplo}
#+latex_header: \newtheorem{exc}[thm]{Exemplo}
#+latex_header: \DeclareMathOperator{\sen}{sen}
#+latex_header: \DeclareMathOperator{\arcsen}{arcsen}

# This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.

#+begin_src python :session :exports none
  import numpy as np
  import matplotlib.pyplot as plt
#+end_src

* Definições básicas

Uma função $f:A\to B$ é dita uma *função real* se $B\subset\mathbb{R}$.
Se além disso $A\subset\mathbb{R}$, diz-se que $f$ é uma *função real de uma variável real*.
De aqui em diante qualquer função será uma função real de uma variável real a menos que se indique explícitamente outra coisa.
Na prática, é comum definir uma função $f$ simplesmente por uma equação da forma
$$f(x)=\text{expressão envolvendo a variável }x\,.$$
Nesse caso, assume-se que o domínio de $f$ é o conjunto de todos os $x\in\mathbb{R}$ para os quais a expressão do lado direito retorna um número real.
O contradomínio de $f$ pode ser em princípio qualquer conjunto que contenha a imagem de $f$; por exemplo, o próprio conjunto $\mathbb{R}$.

#+begin_ex
A equação
$$f(x)=\frac{3}{x-2}$$
define uma função $f$ cujo domínio é o conjunto $A$ formado por todos os $x\in\mathbb{R}$ tais que $x-2\ne 0$. Assim, $A=\mathbb{R}-\{2\}$.
#+end_ex

Uma função $f:A\to \mathbb{R}$ pode ser representada graficamente localizando os pares ordenados $(x,f(x))$, com $x\in A$, no plano cartesiano.
Tipicamente, esse processo gera uma curva, a qual é chamada de *gráfico* de $f$.
Como para cada $x\in A$, existe um único par ordenado $(x,f(x))$, o gráfico de $f$ pode ser intersetado por qualquer reta vertical em no máximo um ponto.

* Funções lineares

Diz-se que uma função $f$ é uma *função linear* se existem constantes $a,b\in\mathbb{R}$ tais que $f(x)=ax+b$.
O domínio de qualquer função linear é $\mathbb{R}$. Se $a\ne 0$, a imagem da função linear $f(x)=ax+b$ é $\mathbb{R}$; caso contrário, a imagem de $f$ é $\{b\}$.
Nesse último caso, diz-se que $f$ é uma *função constante*.

#+begin_ex
A figura [[fig1]] mostra os gráficos das funções lineares $f(x)=2x+1$, $g(x)=-x+2$ e $h(x)=3$. Notamos que em todos os casos, o gráfico é uma reta.
#+end_ex

#+begin_src python :session :tangle yes :exports none :eval no
  x = np.linspace(0,4,50)
  y1 = 2*x+1
  y2 = -x+2
  y3 = 3+x-x
  fig, ax = plt.subplots(1,3,figsize=(10,3))
  ax[0].plot(x,y1,label=r"$y=f(x)$")
  ax[1].plot(x,y2,color="C1",label=r"$y=g(x)$")
  ax[2].plot(x,y3,color="C2",label=r"$y=h(x)$")
  ax[0].legend()
  ax[1].legend()
  ax[2].legend()
  plt.subplots_adjust(wspace=0.3)
  fname = "1-fig1.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig1
#+caption: Gráficos das funções lineares $f(x)=2x+1$, $g(x)=-x+2$ e $h(x)=3$.
#+attr_latex: :width \textwidth
[[./1-fig1.pdf]]

Se uma reta passa por dois pontos $(x_1,y_1)$ e $(x_2,y_2)$, como mostrado na figura [[fig2]], define-se a inclinação dessa reta por
$$m=\frac{\Delta y}{\Delta x}=\frac{y_2-y_1}{x_2-x_1}\,.$$
Pode-se verificar que a inclinação da reta não depende da escolha dos pontos $(x_1,y_1)$ e $(x_2,y_2)$, desde que eles pertençam à reta.
Como o gráfico de uma função linear $f(x)=ax+b$ é uma reta que passa pelos pontos $(0,b)$ e $(1,a+b)$, a inclinação dessa reta será
$$m=\frac{a+b-b}{1-0}=a\,.$$
Portanto, o gráfico da função linear $f(x)=ax+b$ é uma reta com inclinação $a$ que passa pelo ponto $(0,b)$, ou seja, a reta corta o eixo $y$ no valor $y=b$.
#+begin_src python :session :tangle yes :exports none :eval no
  x = np.linspace(0,4,50)
  y = 2*x+1
  fig, ax = plt.subplots(1,1,figsize=(3,3))
  ax.plot(x,y)
  ax.plot(1,3,"o",color="C1")
  ax.plot(3,7,"o",color="C1")
  ax.annotate(r"$(x_1,y_1)$",(0.3,3.5))
  ax.annotate(r"$(x_2,y_2)$",(3.1,6.5))
  ax.axhline(3,color="k",ls="--")
  ax.axvline(3,color="k",ls="--")
  ax.set_xticks([])
  ax.set_yticks([])
  fname = "1-fig2.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig2
#+caption: Inclinação de uma reta.
#+attr_latex: :width 0.4\textwidth
[[./1-fig2.pdf]]

#+begin_ex
Vamos encontrar a função linear cujo gráfico é uma reta que passa pelos pontos $(1,3)$ e $(-2,1)$.
Primeiro encontramos que a inclinação da reta é
$$m=\frac{3-1}{1-(-2)}=\frac{2}{3}\,.$$
Logo, a função linear que procuramos deve ter a forma $f(x)=\frac{2}{3}x+b$.
Para determinar $b$ usamos, por exemplo, o fato de que a reta passa pelo ponto $(1,3)$, ou seja, $f(1)=3$.
Com isso, temos que
$$3=\frac{2}{3}(1)+b\quad\Rightarrow\quad b=\frac{7}{3}\,.$$
Portanto, a função linear desejada é $f(x)=\frac{2}{3}x+\frac{7}{3}$.
#+end_ex

Diz-se que uma função $f:A\to\mathbb{R}$ é *crescente* em um conjunto $E\subset A$ se, para quaisquer $x_1,x_2\in E$ com $x_1< x_2$, tem-se que $f(x_1)< f(x_2)$.
Analogamente, diz-se que $f$ é *decrescente* em um conjunto $E\subset A$ se, para quaisquer $x_1,x_2\in E$ com $x_1< x_2$, tem-se que $f(x_1)> f(x_2)$.

#+begin_ex
Uma função linear $f(x)=ax+b$ é crescente em $\mathbb{R}$ se $a>0$, e é decrescente se $a< 0$.
#+end_ex

* Funções polinomiais

Diz-se que uma função $f$ é uma *função polinomial* se existem constantes $a_0,a_1,\ldots,a_n\in\mathbb{R}$ tais que
$$f(x)=a_nx^n+a_{n-1}x^{n-1}+\cdots+a_1x+a_0\,.$$
Os números $a_0,a_1,\ldots,a_n$ são chamados de *coeficientes*; porém, especialmente o coeficiente $a_0$ é chamado de *termo independente*.
Se $a_n\ne 0$, diz-se que $f$ é uma função polinomial de *grau* $n$.
O domínio de qualquer função polinomial é $\mathbb{R}$.
Se o grau de uma função polinomial $f$ é ímpar, a sua imagem também é $\mathbb{R}$. 
Por outro lado, se o grau de $f$ é par, só uma das seguintes afirmações é verdadeira:

1. existe $x_0\in\mathbb{R}$ tal que $f(x_0)\ge f(x)$ para todo $x\in\mathbb{R}$, ou seja, $f$ atinge seu *máximo absoluto* em um ponto $x_0$.
2. existe $x_0\in\mathbb{R}$ tal que $f(x_0)\le f(x)$ para todo $x\in\mathbb{R}$, ou seja, $f$ atinge seu *mínimo absoluto* em um ponto $x_0$.

No primeiro caso a imagem de $f$ é o intervalo $(-\infty,f(x_0)]$. No segundo caso, a imagem de $f$ é o intervalo $[f(x_0),\infty)$.

#+begin_ex
A figura [[fig3]] mostra o gráfico da função $f_n(x)=x^n$ para alguns valores inteiros $n>0$.
Dessa figura observamos o seguinte:

1. $f_n$ é crescente em $\mathbb{R}$ se $n$ é ímpar; enquanto que $f_n$ é decrescente em $(-\infty,0]$ e crescente em $[0,\infty)$ se $n$ é par.
2. Se $0< x< y$, então $0< x^n< y^n$ para todo inteiro $n>0$.
3. O gráfico de $f_n$ é simétrico em relação à origem se $n$ é ímpar. Por outro lado, se $n$ é par, o gráfico de $f_n$ é simétrico em relação ao eixo $y$.
4. Se $x>1$, então $x^{n+1}>x^n$ para todo inteiro $n>0$.
5. Se $0< x< 1$, então $x^{n+1}< x^n$ para todo inteiro $n>0$.
#+end_ex

#+begin_src python :session :tangle yes :exports none :eval no
  x = np.linspace(-1.2,1.2,50)
  y1 = x
  y2 = x**3
  y3 = x**5
  y4 = x**7
  fig, ax = plt.subplots(1,3,figsize=(10,3))
  ax[0].axhline(0,color="k")
  ax[0].axvline(0,color="k")
  ax[0].plot(x,y1,label=r"$y=x$")
  ax[0].plot(x,y2,label=r"$y=x^3$")
  ax[0].plot(x,y3,label=r"$y=x^5$")
  ax[0].plot(x,y4,label=r"$y=x^7$")
  ax[0].legend()
  y1 = x**2
  y2 = x**4
  y3 = x**6
  y4 = x**8
  fig, ax = plt.subplots(1,2,figsize(6,3))
  ax[1].axhline(0,color="k")
  ax[1].axvline(0,color="k")
  ax[1].plot(x,y1,label=r"$y=x^2$")
  ax[1].plot(x,y2,label=r"$y=x^4$")
  ax[1].plot(x,y3,label=r"$y=x^6$")
  ax[1].plot(x,y4,label=r"$y=x^8$")
  ax[1].legend()
  x = np.linspace(0,1.2,50)
  y1 = x**2
  y2 = x**3
  y3 = x**4
  y4 = x**5
  ax[2].axvline(0,color="k")
  ax[2].axhline(0,color="k")
  ax[2].plot(x,y1,label=r"$y=x^2$")
  ax[2].plot(x,y2,label=r"$y=x^3$")
  ax[2].plot(x,y3,label=r"$y=x^4$")
  ax[2].plot(x,y4,label=r"$y=x^5$")
  ax[2].axvline(1,color="k",ls="--")
  ax[2].legend()
  fname = "1-fig3.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig3
#+caption: Gráficos das funções $f_n(x)=x^n$ para alguns valores de $n$.
#+attr_latex: :width \textwidth
[[./1-fig3.pdf]]

#+begin_ex
Uma função polinomial de grau $2$ é chamada de uma *função quadrática*.
Vamos encontrar a imagem da função quadrática
$$f(x)=2x^2-3x+2\,.$$
Para isso é conveniente escrevermos a expressão de $f$ na forma
$$f(x)=2\left[x^2-\frac{3}{2}x\right]+2\,.$$
Agora vamos completar o quadrado dentro da expressão em colchetes:
\begin{equation*}
  \begin{split}
    f(x)&=2\left[x^2-\frac{3}{2}x+\left(\frac{3}{4}\right)^2-\left(\frac{3}{4}\right)^2\right]+2\\
        &=2\left[\left(x-\frac{3}{4}\right)^2-\left(\frac{3}{4}\right)^2\right]+2\\
    &=2\left(x-\frac{3}{4}\right)^2+\frac{7}{8}\,.
  \end{split}
\end{equation*}
Como $(x-\frac{3}{4})^2\ge 0$ para todo $x\in\mathbb{R}$, o mínimo absoluto de $f$ será atingido quando $x=3/4$.
Além disso, podemos verificar imediatamente que $f(3/4)=7/8$.
Portanto, a imagem de $f$ é o intervalo $[7/8,\infty)$. 
A figura [[fig4]] mostra o gráfico de $f$, que é uma curva chamada de *parábola*.
#+end_ex

#+begin_src python :session :tangle yes :exports none :eval no
  x = np.linspace(-1/2,2,100)
  y = 2*x**2-3*x+2
  fig, ax = plt.subplots(1,1,figsize=(3,3))
  ax.axhline(0,color="k")
  ax.axvline(0,color="k")
  ax.plot(x,y)
  fname = "1-fig4.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig4
#+caption: Gráfico da função quadrática $f(x)=2x^2-3x+2$.
#+attr_latex: :width 0.4\textwidth
[[./1-fig4.pdf]]

Seja $f$ uma função polinomial.
Diz-se que um ponto $a\in\mathbb{R}$ é uma *raiz* de $f$ se $f(a)=0$. 
Geometricamente, as raízes de uma função polinomial são os valores de $x$ nos quais o gráfico da função polinomial interseta com o eixo $x$.
O seguinte resultado, que não provaremos aqui, é uma consequência do chamado *teorema fundamental da álgebra*:

#+begin_thm
Toda função polinomial de grau $n$ tem no máximo $n$ raízes reais.
#+end_thm

As seguintes afirmações também podem ser úteis para determinar as raízes de uma função polinomial:

#+begin_thm
Toda função polinomial de grau ímpar tem pelo menos uma raiz real.
#+end_thm

#+begin_thm
Seja a função polinomial
$$f(x)=a_nx^n+\cdots+a_1x+a_0\,,$$
em que $a_0,a_1,\ldots,a_n\in\mathbb{Z}$, $a_0\ne 0$ e $a_n\ne 0$.
O conjunto das possíveis raízes racionais de $f$ é
$$\left\{\frac{p}{q}:p\text{ é um divisor de }a_0\text{ e }q\text{ é um divisor de }a_n\right\}\,.$$
#+end_thm

#+begin_proof
Sejam $p$ e $q\ne 0$ inteiros tais que $p/q$ seja uma raiz de $f$. Logo, $f(p/q)=0$, ou seja,
\begin{equation}
  \label{eq1}
  a_n\frac{p^n}{q^n}+a_{n-1}\frac{p^{n-1}}{q^{n-1}}+\cdots+a_1\frac{p}{q}+a_0=0
\end{equation}
Multiplicando essa equação por $q^{n-1}$, temos que
$$\frac{a_np^n}{q}+a_{n-1}p^{n-1}+\cdots+a_1pq^{n-2}+a_0q^{n-1}=0\,.$$
Como $a_{n-1}p^{n-1},\ldots,a_1p^{n-2}$ e $a_0q^{n-1}$ são inteiros, o número $\frac{a_np^n}{q}$ também deve ser inteiro para que a equação seja verdadeira.
Logo, $q$ deve ser um divisor de $a_np^n$.
Segue daqui que $q=1$ ou $q$ é um divisor de $a_n$, pois, se $q\ne 1$, podemos assumir que $p$ e $q$ não têm fatores em comum.
Assim, em ambos os casos $q$ é um divisor de $a_n$. Se agora multiplicamos a Eq. (\ref{eq1}) por $\frac{q^n}{p}$ (devemos ter $p\ne 0$, senão a Eq. (\ref{eq1}) seria falsa), temos que
$$a_np^{n-1}+a_{n-1}p^{n-2}q+\cdots+a_1q^{n-1}+a_0\frac{q^n}{p}=0\,.$$
Daqui podemos concluir que $p$ deve ser um divisor de $a_0$.
#+end_proof

#+begin_ex
Vamos encontrar as raízes da função
$$f(x)=x^3-5x^2+2x+8\,.$$
Primeiramente observamos que o conjunto das possíveis raízes racionais de $f$ é $\{\pm 1,\pm 2,\pm 4,\pm 8\}$.
Usando os elementos desse conjunto, podemos verificar que $-1$ é uma raiz de $f$.
Isso quer dizer que a divisão $\frac{f(x)}{x-(-1)}$ é exata. De fato, usando o método de Ruffini, temos que
$$\begin{matrix}
&|&1&-5&2&8\\
-1&|&&-1&6&-8\\
\hline\\
&|&1&-6&8&0
\end{matrix}$$
Logo,
$$\frac{f(x)}{x+1}=x^2-6x+8\quad\Rightarrow\quad f(x)=(x+1)(x^2-6x+8)\,.$$
Para obter as raízes restantes, caso existam, devemos resolver a equação $f(x)=0$ para a variável $x$.
Assim, temos que
$$(x+1)(x^2-6x+8)=0\,.$$
Segue daqui que $x+1=0$ ou $x^2-6x+8=0$. Da primeira igualdade obtemos $x=-1$ (que é a raiz de $f$ que já foi encontrada) e da segunda igualdade obtemos que
$$x=\frac{-(-6)\pm\sqrt{(-6)^2-4(1)(8)}}{2(1)}\,,$$
de onde segue que $x=2$ ou $x=4$. Portanto, as raízes de $f$ são $-1,2$ e $4$.
Consequentemente, o gráfico de $f$ (ver figura [[fig5]]) interseta o eixo $x$ nos valores $x=-1$, $x=2$ e $x=4$.
#+end_ex

#+begin_src python :session :tangle yes :exports none :eval no
  x = np.linspace(-2,5)
  y = x**3-5*x**2+2*x+8
  fig, ax = plt.subplots(1,1,figsize=(3,3))
  ax.axhline(0,color="k")
  ax.axvline(0,color="k")
  ax.plot(x,y)
  fname = "1-fig5.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig5
#+caption: Gráfico da função $f(x)=x^3-5x^2+2x+8$.
#+attr_latex: :width 0.4\textwidth
[[./1-fig5.pdf]]

* Funções racionais

Diz-se que uma função $f$ é uma *função racional* se existem funções polinomiais $p$ e $q$ tais que
$$f(x)=\frac{p(x)}{q(x)}\,.$$
O domínio de $f$ é o conjunto $\{x\in\mathbb{R}:q(x)\ne 0\}$.

#+begin_ex
Vamos determinar o domínio da função racional
$$f(x)=\frac{x^5-2x^3+4x^2-1}{3x^2-4x-4}\,.$$
Para isso, simplesmente notamos que as raízes da função polinomial $g(x)=3x^2-4x-4$ são $x=2$ e $x=-1/3$.
Portanto, o domínio de $f$ é o conjunto $\mathbb{R}-\{2,-1/3\}$.
#+end_ex

#+begin_ex
A figura [[fig6]] mostra o gráfico das funções $f(x)=1/x$ e $g(x)=1/x^2$.
Notamos que $f(x)$ assume valores positivos grandes se consideramos valores de $x$ positivos próximos de $0$.
Além disso, $f(x)$ assume valores negativos grandes se consideramos valores de $x$ negativos próximos de $0$.
Por outro lado, $g(x)$ assume valores grandes positivos se consideramos valores de $x$ próximos de $0$ de qualquer sinal.
#+end_ex

#+begin_src python :session :tangle yes :exports none :eval no
  x1 = np.linspace(-2,-0.1)
  x2 = np.linspace(0.1,2)
  y1 = 1/x1
  y2 = 1/x2
  fig, ax = plt.subplots(1,1,figsize=(3,3))
  ax.axhline(0,color="k")
  ax.axvline(0,color="k")
  ax.plot(x1,y1)
  ax.plot(x2,y2,color="C0",label=r"$y=\frac{1}{x}$")
  y1 = 1/x1**2
  y2 = 1/x2**2
  ax.plot(x1,y1,color="C1")
  ax.plot(x2,y2,color="C1",label=r"$y=\frac{1}{x^2}$")
  ax.set_ylim([-10,10])
  ax.legend(loc="lower right")
  fname = "1-fig6.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig6
#+caption: Gráficos das funções $f(x)=1/x$ e $g(x)=1/x^2$.
#+attr_latex: :width 0.4\textwidth
[[./1-fig6.pdf]]

* Funções algébricas

Dado um inteiro $n>0$, consideremos a função $f_n:[0,\infty)\to[0,\infty)$ definida por $f_n(x)=x^n$.
Da figura [[fig3]] podemos concluir que $f_n$ é sobrejetiva e crescente no seu domínio.
Logo, ela também é injetiva e, por conseguinte, é uma bijeção.
Assim, $f_n$ tem uma inversa $f_n^{-1}:[0,\infty)\to[0,\infty)$ definida por
$$f_n^{-1}(x)=y\quad\Leftrightarrow\quad y^n=x\,.$$
A função $f_n^{-1}$ é chamada de função *raiz \(n\)-ésima* e escreve-se
$$f_n^{-1}(x)=\sqrt[n]{x}\quad\text{ou}\quad f_n^{-1}(x)=x^{1/n}\,.$$
A figura [[fig7]] mostra o gráfico da função $f_n^{-1}$ para alguns valores de $n$.
Desse gráfico podemos concluir o seguinte:

1. $f_n^{-1}$ é crescente no seu domínio, ou seja, se $0< x< y$, então $0< x^{1/n}< y^{1/n}$ para todo inteiro $n>0$.
2. Se $x>1$, então $x^{1/(n+1)}< x^{1/n}$ para todo inteiro $n>0$.
3. Se $0< x<1$, então $x^{1/(n+1)}> x^{1/n}$ para todo inteiro $n>0$.

#+begin_src python :session :tangle yes :exports none :eval no
  x = np.linspace(0,2,100)
  y1 = x**(1/2)
  y2 = x**(1/3)
  y3 = x**(1/4)
  y4 = x**(1/5)
  fig, ax = plt.subplots(1,1,figsize=(3,3))
  ax.axhline(0,color="k")
  ax.axvline(0,color="k")
  ax.plot(x,y1,label=r"$y=x^{1/2}$")
  ax.plot(x,y2,label=r"$y=x^{1/3}$")
  ax.plot(x,y3,label=r"$y=x^{1/4}$")
  ax.plot(x,y4,label=r"$y=x^{1/5}$")
  ax.axvline(1,color="k",ls="--")
  ax.legend()
  fname = "1-fig7.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig7
#+caption: Gráfico das funções $f_n^{-1}(x)=x^{1/n}$ para alguns valores de $n$.
#+attr_latex: :width 0.4\textwidth
[[./1-fig7.pdf]]

Vale ressaltar que a função raiz \(n\)-ésima pode ser definida como uma bijeção de $\mathbb{R}$ em $\mathbb{R}$ no caso em que $n$ é ímpar.
Isso acontece devido a que nesse caso a função $f:\mathbb{R}\to\mathbb{R}$ definida por $f(x)=x^n$ é uma bijeção.

Diz-se que uma função $f$ é uma *função algébrica* se a expressão de $f(x)$ faz uso de no máximo as quatro operações elementares e a operação de radiciação.

#+begin_ex
A função
$$f(x)=\frac{\sqrt{3-2x}}{4x}+\frac{5x^2-3}{x^{1/3}+1}$$
é uma função algébrica. Para determinar o domínio de $f$ devemos levar em conta dois fatos:

1. Não podemos dividir por $0$.
2. Raízes de ordem par só podem ser aplicadas a números não-negativos.
Assim, devemos ter $4x\ne 0$, $x^{1/3}+1\ne 0$ e $3-2x\ge 0$.
Segue daqui que $x\ne 0$, $x\ne -1$ e $x\le 3/2$.
Portanto, o domínio de $f$ é o conjunto $(-\infty,3/2]-\{0,-1\}$.
#+end_ex

* A função valor absoluto

Define-se a função *valor absoluto* por $|x|=\sqrt{x^2}$.
Como $x^2\ge 0$ para todo $x\in\mathbb{R}$, o domínio da função valor absoluto é $\mathbb{R}$.
Além disso, tem-se o seguinte:

1. Se $x\ge 0$, então $\sqrt{x^2}=x$ e, por conseguinte, $|x|=x$.
2. Se $x< 0$, então $\sqrt{x^2}=\sqrt{(-x)^2}=-x$, pois a imagem da função raiz quadrada é o intervalo $[0,\infty)$.
 Logo, nesse caso, $|x|=-x$.
Segue dessas observações que a imagem da função valor absoluto é o intervalo $[0,\infty)$ e também que essa função poderia ter sido definida por
$$|x|=\begin{cases}
x&\text{se }x\ge 0\\
-x&\text{se }x< 0\,. 
\end{cases}$$
A figura [[fig8]] mostra o gráfico da função valor absoluto.

#+begin_src python :session :tangle yes :exports none :eval no
  x = np.linspace(-5,5,100)
  y = np.abs(x)
  fig, ax = plt.subplots(1,1,figsize=(3,3))
  ax.axhline(0,color="k")
  ax.axvline(0,color="k")
  ax.plot(x,y)
  fname = "1-fig8.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig8
#+caption: Gráfico da função valor absoluto.
#+attr_latex: :width 0.4\textwidth
[[./1-fig8.pdf]]

#+attr_latex: :options [Propriedades do valor absoluto]
#+begin_thm
Dados $x,y\in\mathbb{R}$, tem-se que

1. $|x|\ge 0$;
2. $x\le |x|$ e $-x\le |x|$;
3. $|xy|=|x||y|$;
4. $|x+y|\le |x|+|y|$.
#+end_thm
#+begin_proof
Os itens 2 e 3 são consequências diretas da definição da função valor absoluto.

3. [@3] $|xy|=\sqrt{(xy)^2}=\sqrt{x^2y^2}=\sqrt{x^2}\sqrt{y^2}=|x||y|$.
4. Temos que $|x+y|^2=(x+y)^2=x^2+y^2+2xy=|x|^2+|y|^2+2xy$. Como $xy\le |x||y|$, segue que
 $|x+y|^2\le |x|^2+|y|^2+2|x||y|=(|x|+|y|)^2$. Finalmente, como $|x+y|\ge 0$ e $|x|+|y|\ge 0$, temos que $|x+y|\le |x|+|y|$.\qedhere
#+end_proof

O conjunto $\mathbb{R}$ dos números reais pode ser representado graficamente por uma reta.
Nessa reta cada ponto corresponde a um número e vice-versa.
A *distância* entre dois pontos $x,y\in\mathbb{R}$ é definida por
$$d(x,y)=|x-y|\,.$$
Com essa definição de distância, define-se também o *comprimento* de qualquer um dos intervalos $(a,b)$, $(a,b]$, $[a,b)$ ou $[a,b]$ por $|a-b|$.
Podemos verificar que essa distância tem as seguintes propriedades:

1. $d(x,y)=0$ se, e somente se, $x=y$.
2. $d(x,y)=d(y,x)$ para quaisquer $x,y\in\mathbb{R}$.
3. $d(x,z)\le d(x,y)+d(y,z)$ para quaisquer $x,y,z\in\mathbb{R}$.

* Funções trigonométricas

Sejam dois pontos $P=(x_1,y_1)$ e $Q=(x_2,y_2)$ no plano cartesiano, como mostrado na figura [[fig9]].
Notamos que a distância entre esses dois pontos, ou seja, o comprimento do segmento $\overline{PQ}$, é
$$|\overline{PQ}|=\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}\,,$$
em virtude do teorema de Pitágoras.

#+begin_src python :session :tangle yes :exports none :eval no
  x = np.linspace(1,3)
  y = 2*x+1
  fig, ax = plt.subplots(1,1,figsize=(3,3))
  ax.axhline(0,color="k")
  ax.axvline(0,color="k")
  ax.plot(x,y)
  ax.plot(x,3*x/x,color="k",ls="--")
  ax.plot(3*x/x,y,color="k",ls="--")
  ax.plot(1,3,"o",color="C1")
  ax.plot(3,7,"o",color="C1")
  ax.annotate(r"$P$",(0.6,2.4))
  ax.annotate(r"$Q$",(3.2,7))
  ax.annotate(r"$x_2-x_1$",(1.6,2.4))
  ax.annotate(r"$y_2-y_1$",(3.1,5))
  ax.set_xlim([-1,5])
  ax.set_ylim([-1,8])
  ax.set_xticks([])
  ax.set_yticks([])
  fname = "1-fig9.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig9
#+caption: Distância entre dois pontos no plano cartesiano.
#+attr_latex: :width 0.4\textwidth
[[./1-fig9.pdf]]

O conjunto
$$\{(x,y):x^2+y^2=1\}$$
pode ser descrito em palavras como o conjunto de todos os pontos $P$ cuja distância à origem de coordenadas $O=(0,0)$ é igual a $1$. Assim, a representação gráfica desse conjunto
no plano cartesiano é uma circunferência de raio $1$ com centro na origem de coordenadas, a qual é chamada de *circunferência trigonométrica*.
Um ângulo associado a um ponto $P$ da circunferência trigonométrica é definido como o ângulo que parte do semieixo $x$ positivo e chega no segmento $\overline{OP}$ (ver figura [[fig10]]).
Segue daqui que há na verdade infinitos ângulos associados ao ponto $P$.
Vale ressaltar que ângulos no sentido anti-horário são positivos e ângulos no sentido horário são negativos.
Além disso, a medida dos ângulos será feita em radianos a menos que se indique outra coisa. Nessa direção, é importante lembrar da relação $2\pi\,\mathrm{rad}=360^\circ$.

#+begin_src python :session :tangle yes :exports none :eval no
  t = np.linspace(0,2*np.pi)
  x = np.cos(t)
  y = np.sin(t)
  fig, ax = plt.subplots(1,1,figsize=(3,3))
  ax.axhline(0,color="k")
  ax.axvline(0,color="k")
  ax.plot(x,y)
  x = np.linspace(-1/2,0)
  y = -np.sqrt(3)*x
  ax.plot(x,y,color="k",ls="--")
  ax.plot(0,0,"o")
  ax.plot(-1/2,np.sqrt(3)/2,"o",color="C1")
  ax.annotate(r"$O$",(0.05,-0.15))
  ax.annotate(r"$P$",(-1/2-0.1,np.sqrt(3)/2+0.05))
  t = np.linspace(0,2*np.pi/3)
  x = 0.1*np.cos(t)
  y = 0.1*np.sin(t)
  ax.plot(x,y,color="C2")
  t = np.linspace(0,4*np.pi/3)
  x = 0.2*np.cos(t)
  y = -0.2*np.sin(t)
  ax.plot(x,y,color="C3")
  fname = "1-fig10.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig10
#+caption: Dois ângulos associados ao ponto $P$. O ângulo em verde é positivo, enquanto que o ângulo em vermelho é negativo.
#+attr_latex: :width 0.4\textwidth
[[./1-fig10.pdf]]

Se $x\in\mathbb{R}$ é um ângulo associado a um ponto $P=(a,b)$ da circunferência trigonométrica, então define-se o seu *seno* e o seu *cosseno* por
$$\sen x=b\quad\text{e}\quad \cos x=a\,.$$
Como $a,b\in[-1,1]$ para qualquer ponto $P$ da circunferência trigonométrica, tem-se que
$$-1\le \sen x\le 1\quad\text{e}\quad -1\le \cos x\le 1$$
para qualquer $x\in\mathbb{R}$. Assim, colocado de forma mais precisa, a função seno $\sen:\mathbb{R}\to [-1,1]$ e a função cosseno $\cos:\mathbb{R}\to[-1,1]$ são sobrejetivas.

Uma função $f$ é dita uma *função periódica* se existe $c\in\R$ tal que $f(x+c)=f(x)$ para todo $x$ no domínio de $f$.
Nesse caso, o menor valor $T>0$ para o qual se tenha $f(x+T)=f(x)$ é chamado de *período* de $f$.

Usando a circunferência trigonométrica, podemos concluir que as funções seno e cosseno são funções periódicas com período $2\pi$.
Logo, para qualquer $x\in\mathbb{R}$ tem-se que
$$\sen(x+2\pi)=\sen x\quad\text{e}\quad\cos(x+2\pi)=\cos x\,.$$

A seguinte tabela mostra valores de seno e cosseno para alguns ângulos notáveis:

| Ângulo (rad) | Ângulo ($^\circ$) | Seno         | Cosseno      |
|--------------+-------------------+--------------+--------------|
| $0$          | $0$               | $0$          | $1$          |
| $\pi/6$      | $30$              | $1/2$        | $\sqrt{3}/2$ |
| $\pi/4$      | $45$              | $\sqrt{2}/2$ | $\sqrt{2}/2$ |
| $\pi/3$      | $60$              | $\sqrt{3}/2$ | $1/2$        |
| $\pi/2$      | $90$              | $1$          | $0$          |
| $\pi$        | $180$             | $0$          | $-1$         |
| $3\pi/2$     | $270$             | $-1$         | $0$          |
| $2\pi$       | $360$             | $0$          | $1$          |

A figura [[fig11]] mostra os gráficos das funções seno e cosseno.
Dessa figura podemos notar que
$$\sen(-x)=-\sen x\quad\text{e}\quad \cos(-x)=\cos x$$
para qualquer $x\in\mathbb{R}$.

#+begin_src python :session :tangle yes :exports none :eval no
  x = np.linspace(-5*np.pi,5*np.pi,200)
  y1 = np.sin(x)
  y2 = np.cos(x)
  fig, ax = plt.subplots(2,1,figsize=(6,6))
  ax[0].axhline(0,color="k")
  ax[0].axvline(0,color="k")
  ax[0].plot(x,y1,label=r"$y={\rm sen}\,x$")
  ax[0].set_xticks([-4*np.pi,-3*np.pi,-2*np.pi,-np.pi,0,np.pi,2*np.pi,3*np.pi,4*np.pi])
  ax[0].set_xticklabels([r"$-4\pi$",r"$-3\pi$",r"$-2\pi$",r"$-\pi$",r"$0$",r"$\pi$",r"$2\pi$",r"$3\pi$",r"$4\pi$"])
  ax[0].legend(loc="upper right")
  ax[1].axhline(0,color="k")
  ax[1].axvline(0,color="k")
  ax[1].plot(x,y2,color="C1",label=r"$y=\cos\,x$")
  ax[1].set_xticks([-4*np.pi,-3*np.pi,-2*np.pi,-np.pi,0,np.pi,2*np.pi,3*np.pi,4*np.pi])
  ax[1].set_xticklabels([r"$-4\pi$",r"$-3\pi$",r"$-2\pi$",r"$-\pi$",r"$0$",r"$\pi$",r"$2\pi$",r"$3\pi$",r"$4\pi$"])
  ax[1].legend(loc="upper right")
  fname = "1-fig11.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig11
#+caption: Gráficos das funções seno e cosseno.
#+attr_latex: :width 0.8\textwidth
[[./1-fig11.pdf]]

As funções secante e cossecante são definidas respectivamente por
$$\sec x=\frac{1}{\cos x}\quad\text{e}\quad \csc x=\frac{1}{\sen x}\,.$$
Como $\cos x=0$ se $x=(2n+1)\pi/2$, com $n$ inteiro, o domínio da função secante é o conjunto
$$\left\{x\in\mathbb{R}:x\ne(2n+1)\frac{\pi}{2},n\in\mathbb{Z}\right\}\,.$$
De forma análoga, podemos mostrar que o domínio da função cossecante é o conjunto
$$\{x\in\mathbb{R}:x\ne n\pi,n\in\mathbb{Z}\}\,.$$
A figura [[fig12]] mostra os gráficos das funções secante e cossecante.
Notamos dessa figura que essas funções são periódicas, com período $2\pi$.
Além disso, ambas as funções têm como imagem o conjunto $\mathbb{R}-(-1,1)$.

#+begin_src python :session :tangle yes :exports none :eval no
  x1 = np.linspace(-2*np.pi,-3*np.pi/2-0.1)
  x2 = np.linspace(-3*np.pi/2+0.1,-np.pi/2-0.1)
  x3 = np.linspace(-np.pi/2+0.1,np.pi/2-0.1)
  x4 = np.linspace(np.pi/2+0.1,3*np.pi/2-0.1)
  x5 = np.linspace(3*np.pi/2+0.1,2*np.pi)
  fig, ax = plt.subplots(1,2,figsize=(6,3))
  ax[0].axhline(0,color="k")
  ax[0].axvline(0,color="k")
  ax[0].plot(x1,1/np.cos(x1),label=r"$y=\sec\,x$")
  ax[0].plot(x2,1/np.cos(x2),color="C0")
  ax[0].plot(x3,1/np.cos(x3),color="C0")
  ax[0].plot(x4,1/np.cos(x4),color="C0")
  ax[0].plot(x5,1/np.cos(x5),color="C0")
  ax[0].axvline(-3*np.pi/2,color="k",ls="--")
  ax[0].axvline(-np.pi/2,color="k",ls="--")
  ax[0].axvline(np.pi/2,color="k",ls="--")
  ax[0].axvline(3*np.pi/2,color="k",ls="--")
  ax[0].set_xticks([-2*np.pi,-np.pi,0,np.pi,2*np.pi])
  ax[0].set_xticklabels([r"$-2\pi$",r"$-\pi$",r"$0$",r"$\pi$",r"$2\pi$"])
  ax[0].legend(loc="upper right")
  x1 = np.linspace(-2*np.pi+0.1,-np.pi-0.1)
  x2 = np.linspace(-np.pi+0.1,0-0.1)
  x3 = np.linspace(0+0.1,np.pi-0.1)
  x4 = np.linspace(np.pi+0.1,2*np.pi-0.1)
  ax[1].axhline(0,color="k")
  ax[1].axvline(0,color="k")
  ax[1].plot(x1,1/np.sin(x1),color="C1",label=r"$y=\csc\,x$")
  ax[1].plot(x2,1/np.sin(x2),color="C1")
  ax[1].plot(x3,1/np.sin(x3),color="C1")
  ax[1].plot(x4,1/np.sin(x4),color="C1")
  ax[1].axvline(-np.pi,color="k",ls="--")
  ax[1].axvline(np.pi,color="k",ls="--")
  ax[1].set_xticks([-2*np.pi,-np.pi,0,np.pi,2*np.pi])
  ax[1].set_xticklabels([r"$-2\pi$",r"$-\pi$",r"$0$",r"$\pi$",r"$2\pi$"])
  ax[1].legend(loc="upper right")
  fname = "1-fig12.pdf"
  fig.subplots_adjust(wspace=0.3)
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig12
#+caption: Gráficos das funções secante e cossecante.
#+attr_latex: :width 0.8\textwidth
[[./1-fig12.pdf]]

As funções tangente e cotangente são definidas respectivamente por
$$\tan x=\frac{\sen x}{\cos x}\quad\text{e}\quad \cot x=\frac{\cos x}{\sen x}\,.$$
O domínio da tangente é igual ao domínio da secante e o domínio da cotangente coincide com o domínio da cossecante.
A figura [[fig13]] mostra os gráficos das funções tangente e cotangente.
Notamos dessa figura que a imagem dessas funções é $\mathbb{R}$ e que elas são funções periódicas.
Porém, diferentemente das funções seno e cosseno, as funções tangente e cotangente têm período $\pi$.

#+begin_src python :session :tangle yes :exports none :eval no
  x1 = np.linspace(-2*np.pi,-3*np.pi/2-0.1)
  x2 = np.linspace(-3*np.pi/2+0.1,-np.pi/2-0.1)
  x3 = np.linspace(-np.pi/2+0.1,np.pi/2-0.1)
  x4 = np.linspace(np.pi/2+0.1,3*np.pi/2-0.1)
  x5 = np.linspace(3*np.pi/2+0.1,2*np.pi)
  fig, ax = plt.subplots(1,2,figsize=(6,3))
  ax[0].axhline(0,color="k")
  ax[0].axvline(0,color="k")
  ax[0].plot(x1,np.tan(x1),label=r"$y=\tan\,x$")
  ax[0].plot(x2,np.tan(x2),color="C0")
  ax[0].plot(x3,np.tan(x3),color="C0")
  ax[0].plot(x4,np.tan(x4),color="C0")
  ax[0].plot(x5,np.tan(x5),color="C0")
  ax[0].axvline(-3*np.pi/2,color="k",ls="--")
  ax[0].axvline(-np.pi/2,color="k",ls="--")
  ax[0].axvline(np.pi/2,color="k",ls="--")
  ax[0].axvline(3*np.pi/2,color="k",ls="--")
  ax[0].set_xticks([-2*np.pi,-np.pi,0,np.pi,2*np.pi])
  ax[0].set_xticklabels([r"$-2\pi$",r"$-\pi$",r"$0$",r"$\pi$",r"$2\pi$"])
  ax[0].legend(loc="upper right")
  x1 = np.linspace(-2*np.pi+0.1,-np.pi-0.1)
  x2 = np.linspace(-np.pi+0.1,0-0.1)
  x3 = np.linspace(0+0.1,np.pi-0.1)
  x4 = np.linspace(np.pi+0.1,2*np.pi-0.1)
  ax[1].axhline(0,color="k")
  ax[1].axvline(0,color="k")
  ax[1].plot(x1,1/np.tan(x1),color="C1",label=r"$y=\cot\,x$")
  ax[1].plot(x2,1/np.tan(x2),color="C1")
  ax[1].plot(x3,1/np.tan(x3),color="C1")
  ax[1].plot(x4,1/np.tan(x4),color="C1")
  ax[1].axvline(-np.pi,color="k",ls="--")
  ax[1].axvline(np.pi,color="k",ls="--")
  ax[1].set_xticks([-2*np.pi,-np.pi,0,np.pi,2*np.pi])
  ax[1].set_xticklabels([r"$-2\pi$",r"$-\pi$",r"$0$",r"$\pi$",r"$2\pi$"])
  ax[1].legend(loc="upper right")
  fname = "1-fig13.pdf"
  fig.subplots_adjust(wspace=0.3)
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig13
#+caption: Gráficos das funções tangente e cotangente.
#+attr_latex: :width 0.8\textwidth
[[./1-fig13.pdf]]

As funções trigonométricas satisfazem algumas relações, chamadas de *identidades trigonométricas*.
Por exemplo, usando a circunferência trigonométrica, podemos verificar imediatamente que
$$\sen^2x+\cos^2x=1$$
para todo $x\in\mathbb{R}$. Além disso, dividindo essa equação por $\cos^2 x$, obtemos que
$$1+\tan^2x=\sec^2x$$
para todo $x$ no domínio da tangente. De forma análoga podemos obter que
$$1+\cot^2x=\csc^2x$$
para todo $x$ no domínio da cotangente.

#+begin_ex
Se $x\in[\pi,2\pi]$ e $\cos x=3/5$, podemos obter o valor de $\sen x$ usando a identidade trigonométrica $\sen^2x+\cos^2x=1$.
De fato, a partir daqui temos que
$$\sen x=\pm\sqrt{1-\cos^2x}\,.$$
Como devemos ter $\sen x< 0$, pois $x\in[\pi,2\pi]$, então
$$\sen x=-\sqrt{1-\cos^2x}=-\sqrt{1-\frac{9}{25}}=-\frac{4}{5}\,.$$
#+end_ex

Outras identidades trigonométricas importantes são as seguintes: para quaisquer $x,y\in\R$,

1. $\sen(x+y)=\sen x\cos y+\cos x\sen y$;
2. $\cos(x+y)=\cos x\cos y-\sen x\sen y$.

Para justificar essas identidades, consideremos dois pontos $P$ e $Q$ na circunferência trigonométrica, como mostrado no painel esquerdo da figura [[fig13]].
Chamemos o ângulo em verde de $\alpha$ e o ângulo em vermelho de $\beta$.
Logo, temos que $P=(\cos(\alpha+\beta),\sen(\alpha+\beta))$ e $Q=(\cos \alpha,\sen \alpha)$ e, por conseguinte, o comprimento do segmento $\overline{PQ}$ é
\begin{equation*}
  \begin{split}
    |\overline{PQ}|&=\sqrt{[\cos(\alpha+\beta)-\cos \alpha]^2+[\sen(\alpha+\beta)-\sen \alpha]^2}\\
    &=\sqrt{2-2\cos(\alpha+\beta)\cos \alpha-2\sen(\alpha+\beta)\sen \alpha}
  \end{split}
\end{equation*}
Se giramos o conteúdo do painel esquerdo da figura [[fig13]] o ângulo $\alpha$ no sentido horário, obtemos o painel do lado direito dessa figura.
Logo, o comprimento do segmento $\overline{P'Q'}$ é igual ao comprimento do segmento $\overline{PQ}$. Como $P'=(\cos \beta,\sen \beta)$ e $Q'=(1,0)$, temos que
$$|\overline{P'Q'}|=\sqrt{(\cos \beta-1)^2+\sen^2\beta}=\sqrt{2-2\cos \beta}\,.$$
Assim, devemos ter
$$2-2\cos \beta=2-2\cos(\alpha+\beta)\cos \alpha-2\sen(\alpha+\beta)\sen \alpha\,,$$
de onde obtemos que
\begin{equation}
\label{eq2}
\cos \beta=\cos(\alpha+\beta)\cos \alpha+\sen(\alpha+\beta)\sen \alpha\,.
\end{equation}
Como $\alpha$ e $\beta$ são arbitrários, definindo $x=-\alpha$ e $y=\alpha+\beta$, temos que
\begin{equation}
\label{eq3}
\cos(x+y)=\cos y\cos(-x)+\sen y\sen(-x)=\cos x\cos y-\sen x\sen y\,.
\end{equation}
Por outro lado, pondo $\alpha=x$ e $\beta=y$ na Eq. (\ref{eq2}), temos que
$$\cos y=\cos(x+y)\cos x+\sen(x+y)\sen x\,.$$
Logo, usando a Eq. (\ref{eq3}), temos que
$$\cos y=\cos^2x\cos y-\sen x\sen y\cos x+\sen(x+y)\sen x\,.$$
Isolando $\sen(x+y)$, podemos obter finalmente que
$$\sen(x+y)=\sen x\cos y+\cos x\sen y\,.$$

#+begin_src python :session :tangle yes :exports none :eval no
  t = np.linspace(0,2*np.pi)
  x = np.cos(t)
  y = np.sin(t)
  fig, ax = plt.subplots(1,2,figsize=(6.6,3))
  ax[0].axhline(0,color="k")
  ax[0].axvline(0,color="k")
  ax[0].plot(x,y)
  x = np.linspace(-1/2,0)
  y = -np.sqrt(3)*x
  ax[0].plot(x,y,color="k",ls="--")
  x = np.linspace(0,np.sqrt(2)/2)
  y = x
  ax[0].plot(x,y,color="k",ls="--")
  t = np.linspace(0,1)
  x = np.sqrt(2)/2+t*(-1/2-np.sqrt(2)/2)
  y = np.sqrt(2)/2+t*(np.sqrt(3)/2-np.sqrt(2)/2)
  ax[0].plot(x,y,color="C4")
  ax[0].plot(0,0,"o")
  ax[0].plot(-1/2,np.sqrt(3)/2,"o",color="C1")
  ax[0].plot(np.sqrt(2)/2,np.sqrt(2)/2,"o",color="C1")
  ax[0].annotate(r"$O$",(0.05,-0.15))
  ax[0].annotate(r"$P$",(-1/2-0.1,np.sqrt(3)/2+0.05))
  ax[0].annotate(r"$Q$",(np.sqrt(2)/2+0.05,np.sqrt(2)/2+0.05))
  t = np.linspace(0,np.pi/4)
  x = 0.2*np.cos(t)
  y = 0.2*np.sin(t)
  ax[0].plot(x,y,color="C2")
  t = np.linspace(np.pi/4,2*np.pi/3)
  x = 0.3*np.cos(t)
  y = 0.3*np.sin(t)
  ax[0].plot(x,y,color="C3")
  t = np.linspace(0,2*np.pi)
  x = np.cos(t)
  y = np.sin(t)
  ax[1].axhline(0,color="k")
  ax[1].axvline(0,color="k")
  ax[1].plot(x,y)
  x = np.linspace(0,np.cos(5*np.pi/12))
  y = np.tan(5*np.pi/12)*x
  ax[1].plot(x,y,color="k",ls="--")
  t = np.linspace(0,1)
  x = 1+t*(np.cos(5*np.pi/12)-1)
  y = t*np.sin(5*np.pi/12)
  ax[1].plot(x,y,color="C4")
  ax[1].plot(0,0,"o")
  ax[1].plot(np.cos(5*np.pi/12),np.sin(5*np.pi/12),"o",color="C1")
  ax[1].plot(1,0,"o",color="C1")
  ax[1].annotate(r"$O$",(0.05,-0.15))
  ax[1].annotate(r"$P'$",(np.cos(5*np.pi/12)+0.1,np.sin(5*np.pi/12)))
  ax[1].annotate(r"$Q'$",(1-0.2,-0.15))
  t = np.linspace(0,5*np.pi/12)
  x = 0.3*np.cos(t)
  y = 0.3*np.sin(t)
  ax[1].plot(x,y,color="C3")
  fig.subplots_adjust(wspace=0.3)
  fname = "1-fig14.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig14
#+caption: Os segmentos $\overline{PQ}$ e $\overline{P'Q'}$ têm o mesmo comprimento.
#+attr_latex: :width 0.8\textwidth
[[./1-fig14.pdf]]

* Funções trigonométricas inversas

Se $f$ é uma função periódica, então ela não tem inversa, pois não é injetiva. Nesse caso, para que $f$ tenha inversa, deve-se restringir o domínio de $f$ a um conjunto $A$ de tal forma que a função
$f:A\to B$, em que $B$ é a imagem de $f$, seja uma bijeção. Em particular, esse procedimento deve ser realizado para as funções trigonométricas.

Para que a função seno tenha inversa, podemos restringir o seu domínio ao intervalo $[-\pi/2,\pi/2]$ (ver figura [[fig11]]).
Assim, a função $\sen:[-\pi/2,\pi/2]\to[-1,1]$ é uma bijeção e, por conseguinte, tem inversa. A inversa da função seno é a função $\arcsen:[-1,1]\to[-\pi/2,\pi/2]$, chamada de *função arco seno*, definida por
$$\arcsen x=y\quad\Leftrightarrow\quad y\in\left[-\frac{\pi}{2},\frac{\pi}{2}\right]\quad\text{e}\quad \sen y=x\,.$$
A figura [[fig15]] mostra o gráfico da função arco seno. Notamos que ela é crescente no seu domínio e satisfaz a relação
$$\arcsen(-x)=\arcsen(x)$$
para todo $x\in[-1,1]$.

#+begin_src python :session :tangle yes :exports none :eval no
  x = np.linspace(-1,1,200)
  y = np.arcsin(x)
  fig, ax = plt.subplots(1,1,figsize=(3,3))
  ax.axhline(0,color="k")
  ax.axvline(0,color="k")
  ax.plot(x,y)
  ax.set_yticks([-np.pi/2,-np.pi/4,0,np.pi/4,np.pi/2])
  ax.set_yticklabels([r"$-\pi/2$",r"$-\pi/4$",r"$0$",r"$\pi/4$",r"$\pi/2$"])
  fname = "1-fig15.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig15
#+caption: Gráfico da função arco seno.
#+attr_latex: :width 0.4\textwidth
[[./1-fig15.pdf]]

Analogamente ao caso da função seno, notamos que a função $\cos:[0,\pi]\to [-1,1]$ é uma bijeção (ver figura [[fig11]]).
A inversa da função cosseno é a função $\arccos:[-1,1]\to[0,\pi]$, chamada de *função arco cosseno*, definida por
$$\arccos x=y\Leftrightarrow\quad y\in[0,\pi]\quad\text{e}\quad \cos y=x\,.$$
A figura [[fig15]] mostra o gráfico da função arco seno. Notamos que ela é decrescente no seu domínio.

#+begin_src python :session :tangle yes :exports none :eval no
  x = np.linspace(-1,1,200)
  y = np.arccos(x)
  fig, ax = plt.subplots(1,1,figsize=(3,3))
  ax.axhline(0,color="k")
  ax.axvline(0,color="k")
  ax.plot(x,y)
  ax.set_yticks([0,np.pi/4,np.pi/2,3*np.pi/4,np.pi])
  ax.set_yticklabels([r"$0$",r"$\pi/4$",r"$\pi/2$",r"$3\pi/4$",r"$\pi$"])
  fname = "1-fig16.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig16
#+caption: Gráfico da função arco cosseno.
#+attr_latex: :width 0.4\textwidth
[[./1-fig16.pdf]]

A função $\tan:(-\pi/2,\pi/2)\to\R$ é uma bijeção (ver figura [[fig13]]).
A sua inversa é a função $\arctan:\R\to(-\pi/2,\pi/2)$, chamada de *função arco tangente*, definida por
$$\arctan x=y\quad\Leftrightarrow\quad x\in\left(-\frac{\pi}{2},\frac{\pi}{2}\right)\quad\text{e}\quad \tan y=x\,.$$
A figura [[fig16]] mostra o gráfico da função arco tangente. Notamos daqui que essa função é crescente em $\R$ e satisfaz a relação
$$\arctan(-x)=-\arctan x$$
para todo $x\in\R$.

#+begin_src python :session :tangle yes :exports none :eval no
  x = np.linspace(-10,10,200)
  y = np.arctan(x)
  fig, ax = plt.subplots(1,1,figsize=(6,3))
  ax.axhline(0,color="k")
  ax.axvline(0,color="k")
  ax.plot(x,y)
  ax.axhline(np.pi/2,color="k",ls="--")
  ax.axhline(-np.pi/2,color="k",ls="--")
  ax.set_yticks([-np.pi/2,-np.pi/4,0,np.pi/4,np.pi/2])
  ax.set_yticklabels([r"$-\pi/2$",r"$-\pi/4$",r"$0$",r"$\pi/4$",r"$\pi/2$"])
  fname = "1-fig17.pdf"
  fig.savefig(fname,bbox_inches="tight")
  plt.close()
#+end_src

#+name: fig17
#+caption: Gráfico da função arco tangente.
#+attr_latex: :width 0.8\textwidth
[[./1-fig17.pdf]]

#+begin_ex
Para todo $x\in[-1,1]$ podemos verificar imediatamente que
$$\sen(\arcsen x)=x\quad\text{e}\quad \cos(\arccos x)=x\,.$$
Da mesma forma, para todo $x\in\R$, temos que
$$\tan(\arctan x)=x\,.$$
No entanto, as expressões $\arcsen(\sen x)$, $\arccos(\cos x)$ e $\arctan(\tan x)$ podem ser diferentes de $x$. Por exemplo, se
$$E=\arcsen\left(\sen\left(\frac{2\pi}{3}\right)\right)\,,$$
temos que
$$\sen\left(\frac{2\pi}{3}\right)=\sen\left(\frac{\pi}{3}+\frac{\pi}{3}\right)=2\sen\left(\frac{\pi}{3}\right)\cos\left(\frac{\pi}{3}\right)=\frac{\sqrt{3}}{2}\,.$$
Logo,
$$E=\arcsen\left(\frac{\sqrt{3}}{2}\right)=\frac{\pi}{3}\ne \frac{2\pi}{3}\,.$$
#+end_ex
