#+title: Limites
#+author: Max Jauregui
#+language: pt_BR
#+LATEX_CLASS_OPTIONS: [12pt,a4paper]
#+latex_header: \usepackage[portuguese]{babel}
#+latex_header: \usepackage[stable]{footmisc}
#+latex_header: \usepackage{mathabx}
#+latex_header: \usepackage{amsthm}
#+latex_header: \newcommand{\R}{\mathbb{R}}
#+latex_header: \newcommand{\Z}{\mathbb{Z}}
#+latex_header: \newcommand{\Q}{\mathbb{Q}}
#+latex_header: \newcommand{\ds}{\displaystyle}
#+latex_header: \newtheorem{thm}{Teorema}
#+latex_header: \newtheorem{cor}[thm]{Corolário}
#+latex_header: \newtheorem{lem}[thm]{Lema}
#+latex_header: \theoremstyle{definition}
#+latex_header: \newtheorem{ex}[thm]{Exemplo}
#+latex_header: \newtheorem{exc}[thm]{Exemplo}
#+latex_header: \DeclareMathOperator{\sen}{sen}
#+latex_header: \DeclareMathOperator{\arcsen}{arcsen}

# This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/ or send a letter to Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.

# #+begin_src python :session :exports none
#  import numpy as np
#  import matplotlib.pyplot as plt
# #+end_src

* Limite de uma sequência

Um conjunto $X$ é chamado de um *espaço métrico* se existe uma função $d:X\times X\to\R$, chamada de *distância*, que tem as seguintes propriedades:

1. $d(x,y)=0$ se, e somente se, $x=y$;
2. $d(x,y)=d(y,x)$ para quaisquer $x,y\in X$;
3. $d(x,z)\le d(x,y)+d(y,z)$ para quaisquer $x,y,z\in X$.
Usando essas três propriedades temos que, para quaisquer $x,y\in X$,
$$0=d(x,x)\le d(x,y)+d(y,x)=2d(x,y)\,.$$
Portanto, $d(x,y)\ge 0$ para quaisquer $x,y\in X$.

#+begin_ex
O conjunto $\R$ dos números reais é um espaço métrico, no qual a distância é definida por $d(x,y)=|x-y|$ para quaisquer $x,y\in\R$.
#+end_ex

De aqui em diante vamos considerar que $\Z^+$ é o conjunto dos números inteiros positivos e que $X$ é um espaço métrico com distância $d$, a menos que se especifique outra coisa.
Em uma primeira leitura, é conveniente interpretar o espaço métrico $X$ como o conjunto $\R$ ou um subconjunto dele.

Uma *sequência de pontos* de $X$ é uma função $x:\Z^+\to X$.
Para cada $n\in\Z^+$, $x(n)$ é chamado de *termo* \(n\)-ésimo da sequência e é escrito comumente como $x_n$.
Além disso, a própria sequência $x$ é denotada usualmente por $(x_n)_{n\ge 1}$.

#+begin_ex
Se $x_n=3n^2-2$ para cada $n\in\Z^+$, os primeiros $5$ termos da sequência $(x_n)_{n\ge 1}$ são $1,10,25,46$ e $73$.
A sequência $(x_n)_{n\ge 1}$ também pode ser escrita explicitamente como $(3n^2-2)_{n\ge 1}$.
#+end_ex

Diz-se que uma sequência e pontos $(x_n)_{n\ge 1}$ é *limitada* se existem $p\in X$ e $M>0$ tais que $d(x_n,p)< M$ para todo $n\in\Z^+$.

#+begin_ex
A sequência $(\frac{1}{n})_{n\ge 1}$ é limitada pois $d(\frac{1}{n},0)=|\frac{1}{n}|< 5$ para todo $n\in\Z^+$. Por outro lado, a sequência $(n)_{n\ge 1}$ não é limitada, pois para qualquer $M>0$ existe $n\in\Z^+$ tal que $n>M$ e, por conseguinte, $d(n,0)>M$.
#+end_ex

Diz-se que um ponto $a\in X$ é o *limite* de uma sequência se pontos $(x_n)_{n\ge 1}$ se, para todo $\epsilon>0$, pode-se encontrar $N>0$ tal que $n>N$ implica que $d(x_n,a)< \epsilon$. Nesse caso, escreve-se
$$\lim_{n\to\infty}x_n=a$$
ou, de forma simplificada, $x_n\to a$ (essa expressão se lê ``$x_n$ tende para $a$'').

Se uma sequência $(x_n)_{n\ge 1}$ possui um limite, diz-se que ela é *convergente*; caso contrário, diz-se que ela é *divergente*.

#+begin_ex
Vamos mostrar que
$$\lim_{n\to\infty}\frac{1}{n}=0\,.$$
Dado qualquer $\epsilon>0$, sabemos que existe $N\in\Z^+$ tal que $\frac{1}{\epsilon}< N$. Logo, para todo $n>N$, temos que $\frac{1}{\epsilon}< n$ e, por conseguinte, $\frac{1}{n}< \epsilon$. Portanto, $n>N$ implica que $d(\frac{1}{n},0)<\epsilon$, ou seja, $\frac{1}{n}\to 0$.
#+end_ex

Seja $(x_n)_{n\ge 1}$ uma sequência de pontos.
Se para cada $k\in\Z^+$, define-se $n_k\in\Z^+$ de tal forma que $n_k<n_{k+1}$ para todo $k\in\Z^+$, então a sequência $(x_{n_k})_{k\ge 1}$ é chamada de uma *subsequência* de $(x_n)_{n\ge 1}$.

#+begin_thm
Seja $(x_n)_{n\ge 1}$ uma sequência de pontos. Se $x_n\to a$, toda subsequência de $(x_n)_{n\ge 1}$ possui o limite $a$.
#+end_thm

#+begin_proof
Se $x_n\to a$, dado qualquer $\epsilon>0$, existe $N>0$ tal que $n>N$ implica que $d(x_n,a)< \epsilon$.
Se $(x_{n_k})_{k\ge 1}$ é uma subsequência de $(x_n)_{n\ge 1}$, então existe $K\in\Z^+$ tal que $n_K>N$.
Logo, $k>K$ implica que $n_k>N$ e, por conseguinte, $d(x_{n_k},a)< \epsilon$. Portanto, $\displaystyle\lim_{k\to\infty} x_{n_k}=a$.
#+end_proof

#+begin_ex
Exemplos de subsequências de $(\frac{1}{n})_{n\ge 1}$ são os seguintes:

1. $(\frac{1}{2n})_{n\ge 1}$
2. $(\frac{1}{2n+1})_{n\ge 1}$
3. $(\frac{1}{n^2})_{n\ge 1}$
Pelo teorema anterior, todas essas subsequências possuem o limite $0$.
#+end_ex

#+begin_thm
Toda sequência convergente é limitada.
#+end_thm

#+begin_proof
Seja $(x_n)_{n\ge 1}$ uma sequência de pontos que possui o limite $a$.
Logo, existe $N>0$, que podemos considerar inteiro, tal que $n>N$ implica que $d(x_n,a)< 1$.
Definindo
$$M=\max\{1,1+d(x_1,a),1+d(x_2,a),\ldots,1+d(x_N,a)\}\,,$$
temos que $d(x_n,a)< M$ para todo $n\in\Z^+$.
#+end_proof

#+begin_ex
A sequência $(2n-1)_{n\ge 1}$ é divergente, pois não é limitada.
Por outro lado, se $x_n=(-1)^n$ para todo $n\in\Z^+$, a sequência $(x_n)_{n\ge 1}$ é limitada; porém, ela é divergente, pois as subsequências $(x_{2n})_{n\ge 1}$ e $(x_{2n+1})_{n\ge 1}$ possuem respectivamente os limites $1$ e $-1$.
#+end_ex

* Operações com limites

#+begin_thm
Seja $(x_n)_{n\ge 1}$ uma sequência de números reais. Se $x_n\to a$ e $a< c$, então existe $N>0$ tal que $x_n< c$ para todo $n>N$.
#+end_thm

#+begin_proof
Se $x_n\to a$ e $a< c$, então existe $N>0$ tal que $n>N$ implica que $d(x_n,a)< c-a$. Logo, $a-(c-a)< x_n< a+(c-a)$ para todo $n>N$. Portanto, em particular, $x_n< c$ para todo $n>N$.
#+end_proof

#+name: cor1
#+begin_cor
Seja $(x_n)_{n\ge 1}$ uma sequência de números reais. Se $x_n\to a$ e $a> c$, então existe $N>0$ tal que $x_n> c$ para todo $n>N$.
#+end_cor

#+begin_cor
Sejam $(x_n)_{n\ge 1}$ e $(y_n)_{n\ge 1}$ sequências de números reais. Se $x_n\to a$, $y_n\to b$ e $a< b$, então existe $N>0$ tal que $x_n< y_n$ para todo $n>N$.
#+end_cor

#+begin_cor
Sejam $(x_n)_{n\ge 1}$ e $(y_n)_{n\ge 1}$ sequências de números reais. Se $x_n\to a$, $y_n\to b$ e $x_n\le y_n$ para todo $n>N$, então $a\le b$.
#+end_cor

#+attr_latex: :options [Teorema do sanduíche]
#+begin_thm
Sejam $(x_n)_{n\ge 1}$, $(y_n)_{n\ge 1}$ e $(z_n)_{n\ge 1}$ sequências de números reais.
Se $x_n\to a$, $z_n\to a$ e $x_n\le y_n\le z_n$ para todo $n>N$, então $y_n\to a$.
#+end_thm

#+begin_proof
Se $x_n\to a$ e $z_n\to a$, então existe $N_1>0$ tal que $n>N_1$ implica que $d(x_n,a)< \epsilon$ e $d(z_n,a)< \epsilon$. Logo, em particular, temos que $a-\epsilon< x_n$ e $z_n< a+\epsilon$ para todo $n>N_1$.
Se $x_n\le y_n\le z_n$ para todo $n>N$, então pondo $N_2=\max\{N,N_1\}$, temos que
$$a-\epsilon< x_n\le y_n\le z_n< a+\epsilon$$
para todo $n>N_2$. Portanto, $n>N_2$ implica que $d(y_n,a)<\epsilon$, ou seja, $y_n\to a$.
#+end_proof

#+begin_ex
Sabemos que $-1\le \cos n\le 1$ para todo $n\in\Z^+$. Logo,
$$-\frac{1}{n}\le \frac{\cos n}{n}\le \frac{1}{n}$$
para todo $n\in \Z^+$. Como $\frac{1}{n}\to 0$, segue do teorema do sanduíche que 
$$\lim_{n\to\infty}\frac{\cos n}{n}=0\,.$$
#+end_ex

#+name: lem1
#+begin_lem
Para quaisquer $x,y\in\R$, tem-se que $||x|-|y||\le |x-y|$.
#+end_lem

#+begin_proof
Dados $x,y\in\R$ quaisquer, temos que
$$|x|=|y+(x-y)|\le |y|+|x-y|\,.$$
Logo, $|x|-|y|\le |x-y|$. Por outro lado, temos que
$$|y|=|x+(y-x)|\le |x|+|y-x|$$
e, por conseguinte, $|y|-|x|\le |x-y|$. Como $||x|-|y||=\max\{|x|-|y|,|y|-|x|\}$, temos que $||x|-|y||\le |x-y|$.
#+end_proof

#+name: lem2
#+begin_lem
Seja $(x_n)_{n\ge 1}$ uma sequência de números reais. Se $x_n\to 0$ e $(y_n)_{n\ge 1}$ é uma sequência limitada de números reais, então $x_ny_n\to 0$.
#+end_lem

#+begin_proof
Se $(y_n)_{n\ge 1}$ é uma sequência limitada, existe $M>0$ tal que $|y_n|< M$ para todo $n\in\Z^+$.
Se $x_n\to 0$, então, dado qualquer $\epsilon>0$, existe $N>0$ tal que $n>N$ implica que $|x_n|< \frac{\epsilon}{M}$. Logo, para qualquer $n>N$, temos que
$$|x_n||y_n|\le \frac{\epsilon}{M}|y_n|< \frac{\epsilon}{M}M=\epsilon\,.$$
Portanto, $n>N$ implica que $d(x_ny_n,0)<\epsilon$, ou seja, $x_ny_n\to 0$.
#+end_proof

#+name: thm1
#+attr_latex: :options [Operações com limites]
#+begin_thm
Sejam $(x_n)_{n\ge 1}$ e $(y_n)_{n\ge 1}$ sequências de números reais. Se $x_n\to a$ e $y_n\to b$, tem-se o seguinte:

1. $|x_n|\to |a|$;
2. $(x_n+y_n)\to (a+b)$;
3. $x_ny_n\to ab$;
4. $\frac{x_n}{y_n}\to \frac{a}{b}$, desde que se tenha $b\ne 0$.
#+end_thm

#+begin_proof
$\text{ }$

1. Se $x_n\to a$, dado qualquer $\epsilon>0$, existe $N>0$ tal que $n>N$ implica que $|x_n-a|<\epsilon$.
 Logo, para qualquer $n>N$, temos que $||x_n|-|a||\le |x_n-a|<\epsilon$ em virtude do lema [[lem1]]. Portanto, $|x_n|\to |a|$.
2. Se $x_n\to a$ e $y_n\to b$, dado qualquer $\epsilon>0$, existe $N>0$ tal que $n>N$ implica que $|x_n-a|< \frac{\epsilon}{2}$ e $|y_n-a|< \frac{\epsilon}{2}$.
 Logo, para qualquer $n>N$, tem-se que
 $$|(x_n+y_n)-(a+b)|=|(x_n-a)+(y_n-b)|\le |x_n-a|+|y_n-b|< \frac{\epsilon}{2}+\frac{\epsilon}{2}=\epsilon\,.$$
 Portanto, $(x_n+y_n)\to (a+b)$.
3. Primeiramente notamos que
 $$x_ny_n-ab=x_ny_n-x_nb+x_nb-ab=x_n(y_n-b)+(x_n-a)b\,.$$
 Usando isso, vamos provar que, se $x_n\to a$ e $y_n\to b$, então $(x_ny_n-ab)\to 0$ e, por conseguinte, $x_ny_n\to ab$.
 Para isso, notamos que $(y_n-b)\to 0$, $(x_n-a)\to 0$ e, como $x_n\to a$, $(x_n)_{n\ge 1}$ é uma sequência limitada.
 Logo, pelo lema [[lem2]], temos que $x_n(y_n-b)\to 0$ e $(x_n-a)b\to 0$.
 Portanto, pelo item 2, segue que $[x_n(y_n-b)+(x_n-a)b]\to 0$, ou seja, $(x_ny_n-ab)\to 0$.
4. Primeiramente notamos que
 $$\frac{1}{y_n}-\frac{1}{b}=\frac{b-y_n}{y_n b}\,.$$
 Usando isso, vamos provar que, se $y_n\to b$ e $b\ne 0$, então $(\frac{1}{y_n}-\frac{1}{b})\to 0$ e, por conseguinte, $\frac{1}{y_n}\to\frac{1}{b}$.
 Se $y_n\to b$, então, pelo item 1, $|y_n|\to |b|$. Se $b\ne 0$, então $|b|>\frac{|b|}{2}$.
 Logo, pelo corolário [[cor1]], existe $N>0$ tal que $n>N$ implica que $|y_n|>\frac{|b|}{2}$ e, por conseguinte, $|\frac{1}{y_nb}|< \frac{2}{|b|^2}$.
 Segue daqui que a sequência $(\frac{1}{y_nb})_{n\ge 1}$ é limitada. Logo, pelo lema [[lem2]], temos que
 $$\frac{b-y_n}{y_nb}\to 0\,,$$
 pois $(b-y_n)\to 0$. Portanto, $(\frac{1}{y_n}-\frac{1}{b})\to 0$, ou seja, $\frac{1}{y_n}\to \frac{1}{b}$.\qedhere
#+end_proof

#+begin_ex
Para cada $n\in\Z^+$ seja
$$x_n=\frac{2n^2-5}{4n^2+3n-6}\,.$$
Vamos mostrar que a sequência $(x_n)_{n\ge 1}$ é convergente. Para isso, escrevemos
$$\frac{2n^2-5}{4n^2+3n-6}=\frac{n^2(2-\frac{5}{n^2})}{n^2(4+\frac{3}{n}-6)}=\frac{2-\frac{5}{n^2}}{4+\frac{3}{n}-\frac{6}{n^2}}\,.$$
Como $\frac{1}{n}\to 0$, segue que $\frac{5}{n^2}\to 0$, $\frac{3}{n}\to 0$ e $\frac{6}{n^2}\to 0$. Logo, $(2-\frac{5}{n^2})\to 2$ e $(4+\frac{3}{n}-\frac{6}{n^2})\to 4$. Portanto,
$x_n\to \frac{2}{4}=\frac{1}{2}$.
#+end_ex

* Limites de funções

Seja $X$ um espaço métrico. 
Diz-se que um ponto $a\in X$ é um *ponto de acumulação* de um conjunto $A\subset X$ se existe uma sequência $(x_n)_{n\ge 1}$ de pontos de $A$, todos diferentes de $a$, que tem $a$ como limite.

#+begin_ex
Seja $A=\{x\in\R:x=n\text{ ou }x=\frac{1}{n},n\in\Z^+\}$. O ponto $0\in\R$ é um ponto de acumulação de $A$,
pois para cada $n\in\Z^+$ tem-se que $\frac{1}{n}\in A$ e $\frac{1}{n}\to 0$.
#+end_ex

Sejam $X$ e $Y$ espaços métricos, $A\subset X$, $f:A\to Y$ uma função e $a\in X$ um ponto de acumulação de $A$.
Diz-se que um ponto $L\in Y$ é o *limite* de $f(x)$ quando $x$ tende para $a$ se para qualquer sequência $(x_n)_{n\ge 1}$ de pontos de $A-\{a\}$ tal que $x_n\to a$, tem-se que $f(x_n)\to L$.
Nesse caso, escreve-se
$$\lim_{x\to a}f(x)=L\,.$$

#+begin_ex
Vamos mostrar que
$$\lim_{x\to 2}\frac{x^2-4}{x-2}=4\,.$$
Seja $(x_n)_{n\ge 1}$ uma sequência qualquer de pontos de $\R-\{2\}$ tal que $x_n\to 2$. Pondo $f(x)=\frac{x^2-4}{x-2}$, temos que
$$f(x_n)=\frac{x_n^2-4}{x_n-2}=\frac{(x_n-2)(x_n+2)}{x_n-2}=x_n+2\,.$$
Logo, como $x_n\to 2$, $f(x_n)\to 4$. Portanto, $\displaystyle\lim_{x\to 2}f(x)=4$.
#+end_ex

#+begin_ex
Vamos mostrar que o limite
$$\lim_{x\to 0}\frac{|x|}{x}$$
não existe. Para isso, definamos $x_n=\frac{1}{n}$ e $y_n=-\frac{1}{n}$ para cada $n\in\Z^+$. Temos que $x_n,y_n\in\R-\{0\}$ para todo $n\in\Z^+$, $x_n\to 0$ e $y_n\to 0$. No entanto, se $f(x)=\frac{|x|}{x}$, temos que
$$f(x_n)=\frac{|\frac{1}{n}|}{\frac{1}{n}}=\frac{n}{n}=1$$
e
$$f(y_n)=\frac{|\frac{1}{n}|}{\frac{1}{n}}=\frac{-n}{n}=-1\,.$$
Logo, $f(x_n)\to 1$ e $f(y_n)\to -1$. Portanto, não existe $\displaystyle\lim_{x\to 0}f(x)$.
#+end_ex

#+attr_latex: :options [Limite de uma constante]
#+begin_ex
Sejam $X$ um espaço métrico, $a\in X$ um ponto de acumulação de $X$ e $f:X\to\R$ a função definida por $f(x)=c$. Vamos provar que
$$\lim_{x\to a}c=c\,.$$ 
Seja $(x_n)_{n\ge 1}$ uma sequência qualquer de pontos de $X-\{a\}$ tal que $x_n\to a$. Logo, $f(x_n)=c$ e, por conseguinte, $f(x_n)\to c$.
Portanto, $\ds\lim_{x\to a}f(x)=c$. 
#+end_ex

#+attr_latex: :options [Limite de $x$]
#+begin_ex
Sejam $a\in\R$ e $f:\R\to\R$ a função definida por $f(x)=x$. Vamos provar que
$$\lim_{x\to a}x=a\,.$$
Seja $(x_n)_{n\ge 1}$ uma sequência qualquer de números reais diferentes de $a$ tal que $x_n\to a$. Logo, $f(x_n)=x_n$ e, por conseguinte, $f(x_n)\to a$. Portanto, $\ds\lim_{x\to a}f(x)=a$.
#+end_ex

O seguinte teorema é uma consequência direta do teorema [[thm1]]:

#+attr_latex: :options [Operações com limites]
#+begin_thm
Sejam $X$ um espaço métrico, $A\subset X$, $f,g:A\to\R$ funções reais e $a\in X$ um ponto de acumulação de $A$. Se $\ds\lim_{x\to a}f(x)=L$ e $\ds\lim_{x\to a}g(x)=M$, tem-se o seguinte:

1. $\ds\lim_{x\to a}|f(x)|=|L|$;
2. $\ds\lim_{x\to a}[f(x)+g(x)]=L+M$;
3. $\ds\lim_{x\to a}f(x)g(x)=LM$;
4. $\ds\lim_{x\to a}\frac{f(x)}{g(x)}=\frac{L}{M}$, desde que se tenha $M\ne 0$.
#+end_thm

#+begin_ex
Dado $a\in\R$, sabemos que $\ds\lim_{x\to a}x=a$. Logo,
\begin{equation*}
  \begin{split}
    \lim_{x\to a}x^2&=\lim_{x\to a}x\cdot x=a\cdot a=a^2\\
    \lim_{x\to a}x^3&=\lim_{x\to a}x^2\cdot x=a^2\cdot a=a^3\,.
  \end{split}
\end{equation*}
Continuando dessa forma podemos concluir que, para qualquer $n\in\Z^+$, vamos ter $\ds\lim_{x\to a}x^n=a^n$.
Além disso, se $c_n\in\R$ é uma constante, então $\ds\lim_{x\to a}c_nx^n=c_na^n$.
Levando em conta isso, podemos concluir que, se $p:\R\to\R$ é uma função polinomial, então
$$\lim_{x\to a}p(x)=p(a)\,.$$
Finalmente, se $q:\R\to\R$ é uma outra função polinomial tal que $q(a)\ne 0$, então
$$\lim_{x\to a}\frac{p(x)}{q(x)}=\frac{p(a)}{q(a)}\,.$$
#+end_ex

#+begin_ex
Vamos avaliar o limite
$$E=\lim_{x\to 1}\frac{x^3-3x^2+5x-3}{2x^2+x-3}\,.$$
Notamos que $\ds \lim_{x\to 1}(2x^2+x-3)=0$. Logo, $E$ não será o quociente do limite do numerador e o limite do denominador.
Por outro lado, notamos que $\ds\lim_{x\to 1}(x^3-3x^2+5x-3)=0$. Devido a isso, diz-se que $E$ tem a *forma indeterminada* $0/0$.
#+end_ex

